GLSL_SHADER const char HDR_CAS_FRAG[] =
"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform vec4 u_windowCoords;\n"
"uniform vec4 u_nonPowerOfTwo;\n"
"uniform vec4 u_uniformParm0;\n"
"\n"
"varying vec2 var_TexCoord;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 uv = gl_FragCoord.xy;\n"
"    uv *= u_windowCoords.xy;\n"
"    uv *= u_nonPowerOfTwo.xy;\n"
"\n"
"    vec2 texelSize = vec2(\n"
"        u_uniformParm0.x,\n"
"        u_uniformParm0.y\n"
"    );\n"
"\n"
"    float strength = clamp(\n"
"        u_uniformParm0.z,\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    vec3 center = texture2D(\n"
"        u_fragmentMap0,\n"
"        uv\n"
"    ).rgb;\n"
"\n"
"    vec3 north = texture2D(\n"
"        u_fragmentMap0,\n"
"        uv + vec2(0.0, -texelSize.y)\n"
"    ).rgb;\n"
"\n"
"    vec3 south = texture2D(\n"
"        u_fragmentMap0,\n"
"        uv + vec2(0.0, texelSize.y)\n"
"    ).rgb;\n"
"\n"
"    vec3 east = texture2D(\n"
"        u_fragmentMap0,\n"
"        uv + vec2(texelSize.x, 0.0)\n"
"    ).rgb;\n"
"\n"
"    vec3 west = texture2D(\n"
"        u_fragmentMap0,\n"
"        uv + vec2(-texelSize.x, 0.0)\n"
"    ).rgb;\n"
"\n"
"    vec3 average =\n"
"        (north + south + east + west) * 0.25;\n"
"\n"
"    vec3 sharpen =\n"
"        center + (center - average) * strength;\n"
"\n"
"    gl_FragColor = vec4(\n"
"        clamp(sharpen, 0.0, 1.0),\n"
"        1.0\n"
"    );\n"
"}\n"
;