// HDR bloom bright pass with soft knee
GLSL_SHADER const char HDR_BRIGHTPASS_FRAG[] =
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform vec4 u_uniformParm0;\n"
"\n"
"varying vec2 var_TexCoord;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 uv = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"\n"
"    vec3 color = texture2D(u_fragmentMap0, uv).rgb;\n"
"\n"
"    float threshold = u_uniformParm0.x;\n"
"    float knee      = max(u_uniformParm0.y, 0.0001);\n"
"\n"
"    float brightness = max(\n"
"        color.r,\n"
"        max(color.g, color.b)\n"
"    );\n"
"\n"
"    float bloomFactor = smoothstep(\n"
"        threshold - knee,\n"
"        threshold + knee,\n"
"        brightness\n"
"    );\n"
"\n"
"    color *= bloomFactor;\n"
"\n"
"    color = color / (1.0 + brightness);\n"
"\n"
"    gl_FragColor = vec4(color, 1.0);\n"
"}\n"
;
