GLSL_SHADER const char SSGI_TRACE_FRAG[] =
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"\n"
"varying vec2 var_TexCoord;\n"
"\n"
"void main()\n"
"{\n"
"    vec3 color = texture2D(\n"
"        u_fragmentMap0,\n"
"        var_TexCoord\n"
"    ).rgb;\n"
"\n"
"    gl_FragColor = vec4(\n"
"        color,\n"
"        1.0\n"
"    );\n"
"}\n"
;
