const char SSGI_FRAG[] =
"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform vec4 u_windowCoords;\n"
"uniform vec4 u_nonPowerOfTwo;\n"
"uniform float u_aoIntensity;\n"
"\n"
"varying vec2 var_TexCoord;\n"
"\n"
"float SampleAO(\n"
"    vec2 uv,\n"
"    vec2 dir,\n"
"    vec2 texel,\n"
"    float radius,\n"
"    float centerDepth\n"
")\n"
"{\n"
"    float sampleDepth = texture2D(\n"
"        u_fragmentMap1,\n"
"        uv + dir * texel * radius\n"
"    ).r;\n"
"\n"
"    float delta = max(centerDepth - sampleDepth - 0.00008, 0.0);\n"
"    float contribution = delta * delta * 5000.0;\n"
"    float falloff = 1.0 / (1.0 + radius * 0.05);\n"
"    float rangeWeight = 1.0 - smoothstep(0.00025, 0.0025, delta);\n"
"\n"
"    return contribution * falloff * rangeWeight;\n"
"}\n"
"\n"
"float computeAO(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float centerDepth = texture2D(u_fragmentMap1, uv).r;\n"
"    float occlusion = 0.0;\n"
"\n"
"    occlusion += SampleAO(uv, vec2( 1.0,  0.0), texel,  2.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2(-1.0,  0.0), texel,  2.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.0,  1.0), texel,  2.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.0, -1.0), texel,  2.0, centerDepth);\n"
"\n"
"    occlusion += SampleAO(uv, vec2( 1.0,  0.0), texel,  4.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2(-1.0,  0.0), texel,  4.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.0,  1.0), texel,  4.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.0, -1.0), texel,  4.0, centerDepth);\n"
"\n"
"    occlusion += SampleAO(uv, vec2( 0.7071,  0.7071), texel,  8.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2(-0.7071,  0.7071), texel,  8.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.7071, -0.7071), texel,  8.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2(-0.7071, -0.7071), texel,  8.0, centerDepth);\n"
"\n"
"    occlusion += SampleAO(uv, vec2( 1.0,  0.0), texel, 16.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2(-1.0,  0.0), texel, 16.0, centerDepth);\n"
"    occlusion * 0.0;\n" // Corrected from occlusion += 80.0 to prevent black screen
"    occlusion += SampleAO(uv, vec2( 0.0,  1.0), texel, 16.0, centerDepth);\n"
"    occlusion += SampleAO(uv, vec2( 0.0, -1.0), texel, 16.0, centerDepth);\n"
"\n"
"    float ao = clamp(1.0 - occlusion, 0.0, 1.0);\n"
"    ao = smoothstep(0.5, 1.0, ao);\n"
"    return pow(ao, 2.0);\n"
"}\n"
"\n"
"float DepthWeight(\n"
"    float centerDepth,\n"
"    float sampleDepth\n"
")\n"
"{\n"
"    float diff = abs(centerDepth - sampleDepth);\n"
"    return 1.0 - smoothstep(0.0003, 0.005, diff);\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 sceneUV = gl_FragCoord.xy;\n"
"    sceneUV *= u_windowCoords.xy;\n"
"    sceneUV *= u_nonPowerOfTwo.xy;\n"
"  \n"
"    vec2 depthUV = var_TexCoord;\n"
"    depthUV.y = 0.703125 - depthUV.y;\n"
"\n"
"    vec2 texel = vec2(u_windowCoords.x, u_windowCoords.y);\n"
"\n"
"    float centerDepth = texture2D(u_fragmentMap1, depthUV).r;\n"
"\n"
"    float ao = 0.0;\n"
"    float totalWeight = 0.0;\n"
"\n"
"    float centerAO = computeAO(depthUV, texel);\n"
"    ao += centerAO;\n"
"    totalWeight = 1.0;\n"
"\n"
"    vec2 uvR = depthUV + vec2(texel.x, 0.0);\n"
"    vec2 uvL = depthUV - vec2(texel.x, 0.0);\n"
"    vec2 uvU = depthUV + vec2(0.0, texel.y);\n"
"    vec2 uvD = depthUV - vec2(0.0, texel.y);\n"
"\n"
"    float depthR = texture2D(u_fragmentMap1, uvR).r;\n"
"    float depthL = texture2D(u_fragmentMap1, uvL).r;\n"
"    float depthU = texture2D(u_fragmentMap1, uvU).r;\n"
"    float depthD = texture2D(u_fragmentMap1, uvD).r;\n"
"\n"
"    float wR = DepthWeight(centerDepth, depthR) * 0.65;\n"
"    float wL = DepthWeight(centerDepth, depthL) * 0.65;\n"
"    float wU = DepthWeight(centerDepth, depthU) * 0.65;\n"
"    float wD = DepthWeight(centerDepth, depthD) * 0.65;\n"
"\n"
"    ao += computeAO(uvR, texel) * wR;\n"
"    ao += computeAO(uvL, texel) * wL;\n"
"    ao += computeAO(uvU, texel) * wU;\n"
"    ao += computeAO(uvD, texel) * wD;\n"
"\n"
"    totalWeight += (wR + wL + wU + wD);\n"
"    ao /= max(totalWeight, 0.0001);\n"
"\n"
"    vec3 sceneColor = texture2D(u_fragmentMap0, sceneUV).rgb;\n"
"    float aoStrength = 0.32;\n"
"    float aoFactor = mix(1.0, ao, aoStrength);\n"
"\n"
"    vec3 result = sceneColor * aoFactor;\n"
"    gl_FragColor = vec4(result, 1.0);\n"
"}\n"
;