// WebGL 1.0 / GLSL ES 1.00 compatible version
GLSL_SHADER const char GEOMETRIC_NORMAL_VERT[] =
"#version 100\n"
"\n"
"precision highp float;\n"
"\n"
"attribute highp vec4 attr_Vertex;\n"
"attribute highp vec3 attr_Normal;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp mat4 u_modelViewMatrix;\n"
"\n"
"varying highp vec3 var_ViewNormal;\n"
"\n"
"void main(void)\n"
"{\n"
"    var_ViewNormal = normalize(\n"
"        mat3(u_modelViewMatrix) * attr_Normal\n"
"    );\n"
"\n"
"    gl_Position =\n"
"        u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
