// geometric view-space normal buffer
GLSL_SHADER const char ES3_GEOMETRIC_NORMAL_VERT[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in highp vec3 attr_Normal;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp mat4 u_modelViewMatrix;\n"
"\n"
"out highp vec3 var_ViewNormal;\n"
"\n"
"void main(void)\n"
"{\n"
"    var_ViewNormal = normalize(\n"
"        mat3(u_modelViewMatrix) * attr_Normal\n"
"    );\n"
"\n"
"    gl_Position =\n"
"        u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;