// HDR tone mapping with LUT and bloom support
GLSL_SHADER const char ES3_HDR_TONEMAP_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"precision highp sampler3D;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler3D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform highp vec4 u_uniformParm0;\n"
"uniform highp vec4 u_uniformParm1;\n"
"uniform highp vec4 u_uniformParm2;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"vec3 Saturate(vec3 x)\n"
"{\n"
"    return clamp(x, vec3(0.0), vec3(1.0));\n"
"}\n"
"\n"
"float Luminance(vec3 color)\n"
"{\n"
"    return dot(color, vec3(0.2126, 0.7152, 0.0722));\n"
"}\n"
"\n"
"vec3 ACESFitted(vec3 x)\n"
"{\n"
"    return clamp(\n"
"        (x * (2.51 * x + 0.03)) /\n"
"        (x * (2.43 * x + 0.59) + 0.14),\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"}\n"
"\n"
"vec3 ApplySaturation(vec3 color, float saturation)\n"
"{\n"
"    float luma = Luminance(color);\n"
"    return mix(vec3(luma), color, saturation);\n"
"}\n"
"\n"
"vec3 ApplyContrast(vec3 color, float contrast)\n"
"{\n"
"    return (color - vec3(0.5)) * contrast + vec3(0.5);\n"
"}\n"
"\n"
"vec3 ApplyLUT(vec3 color)\n"
"{\n"
"    float enabled = u_uniformParm1.x;\n"
"    float strength = clamp(u_uniformParm1.y, 0.0, 1.0);\n"
"\n"
"    if (enabled < 0.5 || strength <= 0.0)\n"
"    {\n"
"        return color;\n"
"    }\n"
"\n"
"    vec3 coord = clamp(color, vec3(0.0), vec3(1.0));\n"
"    vec3 graded = texture(u_fragmentMap1, coord).rgb;\n"
"\n"
"    return mix(color, graded, strength);\n"
"}\n"
"\n"
"float InterleavedGradientNoise(vec2 screenPos)\n"
"{\n"
"    return fract(\n"
"        52.9829189 * fract(\n"
"            dot(screenPos, vec2(0.06711056, 0.00583715))\n"
"        )\n"
"    );\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 uv = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"\n"
"    vec3 hdrColor = texture(u_fragmentMap0, uv).rgb;\n"
"    vec3 bloomColor = texture(u_fragmentMap2, uv).rgb;\n"
"\n"
"    bloomColor = max(bloomColor, vec3(0.0));\n"
"    bloomColor = min(bloomColor, vec3(8.0));\n"
"    hdrColor = max(hdrColor, vec3(0.0));\n"
"\n"
"    float exposure = max(\n"
"        texture(u_fragmentMap3, vec2(0.5, 0.5)).r,\n"
"        0.0001\n"
"    );\n"
"\n"
"    float gammaValue = max(u_uniformParm0.y, 0.0001);\n"
"    float saturation = max(u_uniformParm0.z, 0.0);\n"
"    float contrast = max(u_uniformParm0.w, 0.0);\n"
"    float bloomStrength = max(u_uniformParm1.w, 0.0);\n"
"\n"
"    hdrColor += bloomColor * bloomStrength;\n"
"    hdrColor *= exposure;\n"
"\n"
"    vec3 color = ACESFitted(hdrColor);\n"
"    color = ApplySaturation(color, saturation);\n"
"    color = ApplyContrast(color, contrast);\n"
"    color = Saturate(color);\n"
"    color = ApplyLUT(color);\n"
"    color = pow(color, vec3(1.0 / gammaValue));\n"
"\n"
"    float noise = InterleavedGradientNoise(gl_FragCoord.xy);\n"
"    color += (noise - 0.5) * (1.0 / 255.0);\n"
"    color = Saturate(color);\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0);\n"
"}\n"
;