// HDR luminance downsample 4x4 average
GLSL_SHADER const char ES3_HDR_DOWNSAMPLE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform highp vec4 u_uniformParm0;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 uv = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"\n"
"    vec2 texelSize = u_uniformParm0.xy;\n"
"\n"
"    vec3 color = vec3(0.0);\n"
"\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-1.5, -1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-0.5, -1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 0.5, -1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 1.5, -1.5)).rgb;\n"
"\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-1.5, -0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-0.5, -0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 0.5, -0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 1.5, -0.5)).rgb;\n"
"\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-1.5,  0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-0.5,  0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 0.5,  0.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 1.5,  0.5)).rgb;\n"
"\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-1.5,  1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2(-0.5,  1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 0.5,  1.5)).rgb;\n"
"    color += texture(u_fragmentMap0, uv + texelSize * vec2( 1.5,  1.5)).rgb;\n"
"\n"
"    color *= 0.0625;\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0);\n"
"}\n"
;