GLSL_SHADER const char ES3_HDR_EXPOSURE_FRAG[] =
"#version 300 es\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform highp vec4 u_uniformParm0;\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main()\n"
"{\n"
"    float lum = max(\n"
"        texture(\n"
"            u_fragmentMap0,\n"
"            vec2(0.5, 0.5)\n"
"        ).r,\n"
"        0.01\n"
"    );\n"
"\n"
"float middleGray = u_uniformParm0.x;\n"
"float exposureMin = u_uniformParm0.y;\n"
"float exposureMax = u_uniformParm0.z;\n"
"\n"
"float exposure = clamp(\n"
"    middleGray / lum,\n"
"    exposureMin,\n"
"    exposureMax\n"
");\n"
"\n"
"float previousExposure =\n"
"    texture(\n"
"        u_fragmentMap1,\n"
"        vec2(0.5, 0.5)\n"
"    ).r;\n"
"\n"
"float adaptedExposure =\n"
"    mix(\n"
"        max(previousExposure, 1.0),\n"
"        exposure,\n"
"        0.25\n"
"    );\n"
"\n"
"    _gl_FragColor = vec4(\n"
"        adaptedExposure,\n"
"        adaptedExposure,\n"
"        adaptedExposure,\n"
"        1.0\n"
"    );\n"
"}\n"
;