// HDR luminance extraction
GLSL_SHADER const char ES3_HDR_LUMINANCE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float Luminance(vec3 color)\n"
"{\n"
"    return dot(color, vec3(0.2126, 0.7152, 0.0722));\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 uv = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"\n"
"    vec3 hdrColor = texture(u_fragmentMap0, uv).rgb;\n"
"    hdrColor = max(hdrColor, vec3(0.0));\n"
"\n"
"    float lum = Luminance(hdrColor);\n"
"\n"
"    _gl_FragColor = vec4(lum, lum, lum, 1.0);\n"
"}\n"
;