GLSL_SHADER const char ES3_SSGI_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"\n"
"uniform float u_aoIntensity;\n"
"uniform float u_aoRadius;\n"
"uniform float u_aoThickness;\n"
"uniform float u_aoNormalReject;\n"
"uniform float u_aoSamples;\n"
"uniform vec4 u_projectionParams;\n"
"uniform int u_gtaoPass;\n"
"uniform int u_gtaoHistoryValid;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(\n"
"    float depth\n"
")\n"
"{\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"\n"
"    return abs(\n"
"        u_projectionParams.w /\n"
"        (ndcZ + u_projectionParams.z)\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(\n"
"    vec2 uv,\n"
"    float depth\n"
")\n"
"{\n"
"    float viewDepth =\n"
"        ReconstructViewDepth(depth);\n"
"\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"\n"
"    return vec3(\n"
"        ndc.x * viewDepth / u_projectionParams.x,\n"
"        ndc.y * viewDepth / u_projectionParams.y,\n"
"        -viewDepth\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewNormal(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float dC = texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r;\n"
"\n"
"    float dL = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dR = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dD = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float dU = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    vec3 pC = ReconstructViewPosition(uv, dC);\n"
"\n"
"    vec3 pL = ReconstructViewPosition(\n"
"        uv - vec2(texel.x, 0.0),\n"
"        dL\n"
"    );\n"
"\n"
"    vec3 pR = ReconstructViewPosition(\n"
"        uv + vec2(texel.x, 0.0),\n"
"        dR\n"
"    );\n"
"\n"
"    vec3 pD = ReconstructViewPosition(\n"
"        uv - vec2(0.0, texel.y),\n"
"        dD\n"
"    );\n"
"\n"
"    vec3 pU = ReconstructViewPosition(\n"
"        uv + vec2(0.0, texel.y),\n"
"        dU\n"
"    );\n"
"\n"
"    vec3 dx =\n"
"        length(pR - pC) < length(pC - pL)\n"
"        ? pR - pC\n"
"        : pC - pL;\n"
"\n"
"    vec3 dy =\n"
"        length(pU - pC) < length(pC - pD)\n"
"        ? pU - pC\n"
"        : pC - pD;\n"
"\n"
"    vec3 normal = normalize(\n"
"        cross(dx, dy)\n"
"    );\n"
"\n"
"    if (normal.z > 0.0)\n"
"    {\n"
"        normal = -normal;\n"
"    }\n"
"\n"
"    return normal;\n"
"}\n"
"\n"
"float DebugHorizonSearch(\n"
"    vec2 uv,\n"
"    vec2 dir,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float centerRawDepth = texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r;\n"
"\n"
"    vec3 centerPos = ReconstructViewPosition(\n"
"        uv,\n"
"        centerRawDepth\n"
"    );\n"
"\n"
"    vec3 centerNormal =\n"
"        ReconstructViewNormal(\n"
"            uv,\n"
"            texel\n"
"        );\n"
"\n"
"    float maxHorizon = 0.0;\n"
"\n"
"    for (int i = 1; i <= 8; i++)\n"
"    {\n"
"        float stepRadius =\n"
"            float(i) * 2.0 * u_aoRadius;\n"
"\n"
"        vec2 sampleUV =\n"
"            uv + dir * texel * stepRadius;\n"
"\n"
"        if (sampleUV.x <= 0.0 ||\n"
"            sampleUV.x >= 1.0 ||\n"
"            sampleUV.y <= 0.0 ||\n"
"            sampleUV.y >= 1.0)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float sampleRawDepth = texture(\n"
"            u_fragmentMap1,\n"
"            sampleUV\n"
"        ).r;\n"
"\n"
"        if (sampleRawDepth >= 0.99999)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        vec3 samplePos = ReconstructViewPosition(\n"
"            sampleUV,\n"
"            sampleRawDepth\n"
"        );\n"
"\n"
"        vec3 delta = \n"
"            samplePos - centerPos;\n"
"\n"
"        float viewDistance =\n"
"            length(delta);\n"
"\n"
"        if (viewDistance <= 0.0001)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float depthSeparation = abs(\n"
"            samplePos.z - centerPos.z\n"
"        );\n"
"\n"
"        float thicknessLimit =\n"
"            max(4.0, 32.0 * u_aoThickness);\n"
"\n"
"        float thicknessWeight =\n"
"            1.0 - smoothstep(\n"
"                thicknessLimit * 0.5,\n"
"                thicknessLimit,\n"
"                depthSeparation\n"
"            );\n"
"\n"
"        float rangeLimit =\n"
"            max(16.0, 128.0 * u_aoRadius);\n"
"\n"
"        float distanceWeight =\n"
"            1.0 - smoothstep(\n"
"                rangeLimit * 0.25,\n"
"                rangeLimit,\n"
"                viewDistance\n"
"            );\n"
"\n"
"        vec3 sampleDir =\n"
"            delta / viewDistance;\n"
"\n"
"        float horizonResponse = max(\n"
"            dot(centerNormal, sampleDir),\n"
"            0.0\n"
"        );\n"
"\n"
"        horizonResponse *=\n"
"            thicknessWeight * distanceWeight;\n"
"\n"
"        maxHorizon = max(\n"
"            maxHorizon,\n"
"            horizonResponse\n"
"        );\n"
"    }\n"
"\n"
"    return clamp(\n"
"        maxHorizon,\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructNormal(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float dL = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dR = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dD = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float dU = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float normalDepthScale = 450.0;\n"
"\n"
"    vec3 dx = vec3(\n"
"        1.0,\n"
"        0.0,\n"
"        (dR - dL) * normalDepthScale\n"
"    );\n"
"\n"
"    vec3 dy = vec3(\n"
"        0.0,\n"
"        1.0,\n"
"        (dU - dD) * normalDepthScale\n"
"    );\n"
"\n"
"    vec3 n = normalize(\n"
"        cross(dx, dy)\n"
"    );\n"
"\n"
"    return n;\n"
"}\n"
"\n"
"float SampleOcclusion(\n"
"    vec2 uv,\n"
"    vec2 dir,\n"
"    vec2 texel,\n"
"    float radius,\n"
"    float centerDepth,\n"
"    vec3 centerNormal\n"
")\n"
"{\n"
"    vec2 sampleUV =\n"
"        uv + dir * texel * radius;\n"
"\n"
"float sampleDepth = ReconstructViewDepth(\n"
"    texture(\n"
"        u_fragmentMap1,\n"
"        sampleUV\n"
"    ).r\n"
");\n"
"\n"
"    float delta =\n"
"        centerDepth - sampleDepth;\n"
"\n"
"    delta = max(\n"
"        delta - 0.00008,\n"
"        0.0\n"
"    );\n"
"\n"
"    float contactWeight = smoothstep(\n"
"        0.0,\n"
"        0.00035,\n"
"        delta\n"
"    );\n"
"\n"
"    float thicknessWeight =\n"
"        1.0 - smoothstep(\n"
"            0.0008 * u_aoThickness,\n"
"            0.0030 * u_aoThickness,\n"
"            delta\n"
"        );\n"
"\n"
"    vec3 sampleNormal = ReconstructNormal(\n"
"        sampleUV,\n"
"        texel\n"
"    );\n"
"\n"
"    float ndot = clamp(\n"
"        dot(centerNormal, sampleNormal),\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    float normalWeight = mix(\n"
"        u_aoNormalReject,\n"
"        1.0,\n"
"        smoothstep(\n"
"            0.15,\n"
"            0.85,\n"
"            ndot\n"
"        )\n"
"    );\n"
"\n"
"    float radiusWeight =\n"
"        1.0 /\n"
"        (1.0 + radius * 0.1);\n"
"\n"
"    float contribution =\n"
"        delta * delta * 5000.0;\n"
"\n"
"    return\n"
"        contribution *\n"
"        contactWeight *\n"
"        thicknessWeight *\n"
"        normalWeight *\n"
"        radiusWeight;\n"
"}\n"
"\n"
"float ComputeAO(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"float centerDepth =\n"
"ReconstructViewDepth(\n"
"    texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r\n"
");\n"
"\n"
"    vec3 centerNormal = ReconstructNormal(\n"
"        uv,\n"
"        texel\n"
"    );\n"
"\n"
"    vec2 dirs[8];\n"
"\n"
"    dirs[0] = vec2( 1.0,  0.0);\n"
"    dirs[1] = vec2(-1.0,  0.0);\n"
"    dirs[2] = vec2( 0.0,  1.0);\n"
"    dirs[3] = vec2( 0.0, -1.0);\n"
"    dirs[4] = vec2( 0.7071,  0.7071);\n"
"    dirs[5] = vec2(-0.7071,  0.7071);\n"
"    dirs[6] = vec2( 0.7071, -0.7071);\n"
"    dirs[7] = vec2(-0.7071, -0.7071);\n"
"\n"
"    float occlusion = 0.0;\n"
"\n"
"    int directions = clamp(\n"
"        int(u_aoSamples),\n"
"        1,\n"
"        8\n"
"    );\n"
"\n"
"for (int i = 0; i < directions; i++)\n"
"\n"
"    {\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            2.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            4.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            8.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            16.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"    }\n"
"\n"
"occlusion *= (80.0 * u_aoIntensity);\n"
"\n"
"    float ao = clamp(\n"
"        1.0 - occlusion,\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    ao = smoothstep(\n"
"        0.05,\n"
"        1.0,\n"
"        ao\n"
"    );\n"
"\n"
"    ao = pow(\n"
"        ao,\n"
"        2.0\n"
"    );\n"
"\n"
"    return ao;\n"
"}\n"
"\n"
"float DepthWeight(\n"
"    float centerDepth,\n"
"    float sampleDepth\n"
")\n"
"{\n"
"    float diff = abs(\n"
"        centerDepth - sampleDepth\n"
"    );\n"
"\n"
"    return 1.0 - smoothstep(\n"
"        0.00025,\n"
"        0.0025,\n"
"        diff\n"
"    );\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 sceneUV = gl_FragCoord.xy;\n"
"    sceneUV *= u_windowCoords.xy;\n"
"    sceneUV *= u_nonPowerOfTwo.xy;\n"
"\n"
"    vec2 depthUV = var_TexCoord;\n"
"    depthUV.y = 0.703125 - depthUV.y;\n"
"\n"
"    vec2 texel = vec2(\n"
"        u_windowCoords.x,\n"
"        u_windowCoords.y\n"
"    );\n"
"\n"
"    float centerDepth = texture(\n"
"        u_fragmentMap1,\n"
"        depthUV\n"
"    ).r;\n"
"\n"
"    float ao = 0.0;\n"
"    float totalWeight = 0.0;\n"
"\n"
"    float centerAO = ComputeAO(\n"
"        depthUV,\n"
"        texel\n"
"    );\n"
"\n"
"    ao += centerAO;\n"
"    totalWeight += 1.0;\n"
"\n"
"    vec2 uvR = depthUV + vec2( texel.x, 0.0);\n"
"    vec2 uvL = depthUV - vec2( texel.x, 0.0);\n"
"    vec2 uvU = depthUV + vec2(0.0, texel.y);\n"
"    vec2 uvD = depthUV - vec2(0.0, texel.y);\n"
"\n"
"    float depthR = texture(u_fragmentMap1, uvR).r;\n"
"    float depthL = texture(u_fragmentMap1, uvL).r;\n"
"    float depthU = texture(u_fragmentMap1, uvU).r;\n"
"    float depthD = texture(u_fragmentMap1, uvD).r;\n"
"\n"
"    float wR = DepthWeight(centerDepth, depthR) * 0.65;\n"
"    float wL = DepthWeight(centerDepth, depthL) * 0.65;\n"
"    float wU = DepthWeight(centerDepth, depthU) * 0.65;\n"
"    float wD = DepthWeight(centerDepth, depthD) * 0.65;\n"
"\n"
"    ao += ComputeAO(uvR, texel) * wR;\n"
"    ao += ComputeAO(uvL, texel) * wL;\n"
"    ao += ComputeAO(uvU, texel) * wU;\n"
"    ao += ComputeAO(uvD, texel) * wD;\n"
"\n"
"    totalWeight +=\n"
"        wR + wL + wU + wD;\n"
"\n"
"    ao /= max(\n"
"        totalWeight,\n"
"        0.0001\n"
"    );\n"
"\n"
"float h0 = DebugHorizonSearch(\n"
"    depthUV,\n"
"    vec2( 1.0, 0.0 ),\n"
"    texel\n"
");\n"
"\n"
"float h1 = DebugHorizonSearch(\n"
"    depthUV,\n"
"    vec2( -1.0, 0.0 ),\n"
"    texel\n"
");\n"
"\n"
"float h2 = DebugHorizonSearch(\n"
"    depthUV,\n"
"    vec2( 0.0, 1.0 ),\n"
"    texel\n"
");\n"
"\n"
"float h3 = DebugHorizonSearch(\n"
"    depthUV,\n"
"    vec2( 0.0, -1.0 ),\n"
"    texel\n"
");\n"
"\n"
"float occlusion =\n"
"    (h0 + h1 + h2 + h3) * 0.25;\n"
"\n"
"occlusion = clamp(\n"
"    occlusion * u_aoIntensity * 2.0,\n"
"    0.0,\n"
"    1.0\n"
");\n"
"\n"
"float visibility =\n"
"    1.0 - occlusion;\n"
"\n"
"vec3 sceneColor = texture(\n"
"    u_fragmentMap0,\n"
"    sceneUV\n"
").rgb;\n"
"\n"
"float storedVisibility = texture(\n"
"    u_fragmentMap2,\n"
"    sceneUV\n"
").r;\n"
"\n"
"if (u_gtaoPass == 0)\n"
"{\n"
"    float temporalVisibility = visibility;\n"
"\n"
"    if (u_gtaoHistoryValid != 0)\n"
"    {\n"
"        temporalVisibility = mix(\n"
"            visibility,\n"
"            storedVisibility,\n"
"            0.8\n"
"        );\n"
"    }\n"
"\n"
"    _gl_FragColor = vec4(\n"
"        temporalVisibility,\n"
"        temporalVisibility,\n"
"        temporalVisibility,\n"
"        1.0\n"
"    );\n"
"    return;\n"
"}\n"
"\n"
"float gtaoStrength = 0.25;\n"
"\n"
"float aoFactor = mix(\n"
"    1.0,\n"
"    storedVisibility,\n"
"    gtaoStrength\n"
");\n"
"\n"
"vec3 result = sceneColor * aoFactor;\n"
"\n"
"_gl_FragColor = vec4(result, 1.0);\n"
"}\n"
;