GLSL_SHADER const char ES3_SSGI_TRACE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0; // Radiance\n"
"uniform sampler2D u_fragmentMap1; // Depth\n"
"uniform sampler2D u_fragmentMap2; // Normals\n"
"uniform sampler2D u_fragmentMap3; // History\n"
"\n"
"uniform highp vec4 u_projectionParams;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform int u_gtaoHistoryValid;\n"
"uniform highp mat4 u_ssgiCurrentViewToPreviousClip;\n"
"uniform highp vec4 u_uniformParm0;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(float depth) {\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"    return abs(u_projectionParams.w / (ndcZ + u_projectionParams.z));\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(vec2 uv, float depth) {\n"
"    float viewDepth = ReconstructViewDepth(depth);\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"    return vec3(ndc.x * viewDepth / u_projectionParams.x, ndc.y * viewDepth / u_projectionParams.y, -viewDepth);\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(vec2 uv) {\n"
"    vec4 encodedNormalSample = texture(u_fragmentMap2, uv);\n"
"    if (encodedNormalSample.a < 0.5) return vec3(0.0, 0.0, 0.0);\n"
"    vec3 normal = encodedNormalSample.xyz * 2.0 - 1.0;\n"
"    float lenSq = dot(normal, normal);\n"
"    if (lenSq < 0.0001) return vec3(0.0, 0.0, -1.0);\n"
"    return normal * inversesqrt(lenSq);\n"
"}\n"
"\n"
"vec2 ProjectViewPosition(vec3 viewPosition) {\n"
"    float safeDepth = max(-viewPosition.z, 0.0001);\n"
"    vec2 ndc = vec2(viewPosition.x * u_projectionParams.x / safeDepth, viewPosition.y * u_projectionParams.y / safeDepth);\n"
"    return ndc * 0.5 + 0.5;\n"
"}\n"
"\n"
"float InterleavedGradientNoise(vec2 pixelPosition) {\n"
"    return fract(52.9829189 * fract(dot(pixelPosition, vec2(0.06711056, 0.00583715))));\n"
"}\n"
"\n"
"vec4 TraceRadiance(vec3 rayOrigin, vec3 rayDirection) {\n"
"    const int TRACE_STEP_COUNT = 24;\n"
"    const float TRACE_STEP_LENGTH = 0.0416667;\n"
"    float previousDepthDifference = -1.0;\n"
"    bool previousDepthValid = false;\n"
"    for (int stepIndex = 1; stepIndex <= TRACE_STEP_COUNT; ++stepIndex) {\n"
"        float rayDistance = float(stepIndex) * TRACE_STEP_LENGTH;\n"
"        vec3 testPosition = rayOrigin + rayDirection * rayDistance;\n"
"        vec2 testScreenUV = ProjectViewPosition(testPosition);\n"
"        if (testScreenUV.x <= 0.0 || testScreenUV.x >= 1.0 || testScreenUV.y <= 0.0 || testScreenUV.y >= 1.0) break;\n"
"        vec2 testDepthUV = testScreenUV * u_nonPowerOfTwo.xy;\n"
"        float sampledRawDepth = texture(u_fragmentMap1, testDepthUV).r;\n"
"        if (sampledRawDepth >= 0.999999) { previousDepthValid = false; continue; }\n"
"        vec3 sampledScenePosition = ReconstructViewPosition(testScreenUV, sampledRawDepth);\n"
"        float signedDepthDifference = sampledScenePosition.z - testPosition.z;\n"
"        float hitThickness = max(TRACE_STEP_LENGTH * 1.0, abs(sampledScenePosition.z) * 0.002);\n"
"        bool crossedSurface = previousDepthValid && previousDepthDifference <= 0.0 && signedDepthDifference > 0.0;\n"
"        bool thinSurfaceHit = signedDepthDifference > 0.0 && signedDepthDifference < hitThickness;\n"
"        vec3 hitNormal = DecodeGeometricNormal(testScreenUV);\n"
"        if (dot(hitNormal, hitNormal) < 0.25) { previousDepthDifference = signedDepthDifference; previousDepthValid = true; continue; }\n"
"        float hitFacing = max(dot(hitNormal, -rayDirection), 0.0);\n"
"        if ((crossedSurface || thinSurfaceHit) && hitFacing > 0.25) {\n"
"            vec3 hitRadiance = texture(\n"
"                u_fragmentMap0,\n"
"                testScreenUV\n"
"            ).rgb;\n"
"\n"
"            float hitLuminance = dot(\n"
"                hitRadiance,\n"
"                vec3(0.2126, 0.7152, 0.0722)\n"
"            );\n"
"\n"
"            const float radianceLimit = 2.0;\n"
"\n"
"            if (hitLuminance > radianceLimit)\n"
"            {\n"
"                hitRadiance = hitRadiance *\n"
"                    (radianceLimit /\n"
"                    max(hitLuminance, 0.0001));\n"
"            }\n"
"\n"
"            return vec4(\n"
"                hitRadiance * hitFacing,\n"
"                hitFacing\n"
"            );\n"
"        }\n"
"        previousDepthDifference = signedDepthDifference;\n"
"        previousDepthValid = true;\n"
"    }\n"
"    return vec4(0.0);\n"
"}\n"
"\n"
"void main(void) {\n"
"vec2 depthUV = vec2(\n"
"    var_TexCoord.x * u_nonPowerOfTwo.x,\n"
"    (1.0 - var_TexCoord.y) * u_nonPowerOfTwo.y\n"
");\n"
"    vec2 screenUV = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"    float centerRawDepth = texture(u_fragmentMap1, depthUV).r;\n"
"\n"
"    if (centerRawDepth >= 0.999999) {\n"
"        _gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 centerPosition = ReconstructViewPosition(screenUV, centerRawDepth);\n"
"    vec3 centerNormal = DecodeGeometricNormal(screenUV);\n"
"    if (dot(centerNormal, centerNormal) < 0.25) {\n"
"        _gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);\n"
"        return;\n"
"    }\n"
"\n"
"    // --- RAY TRACING --- \n"
"    vec3 helperAxis = abs(centerNormal.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(0.0, 1.0, 0.0);\n"
"    vec3 tangent = normalize(cross(helperAxis, centerNormal));\n"
"    vec3 bitangent = normalize(cross(centerNormal, tangent));\n"
"    float rotationNoise = InterleavedGradientNoise(gl_FragCoord.xy);\n"
"    float rotAngle = rotationNoise * 6.2831853;\n"
"    float sinA = sin(rotAngle), cosA = cos(rotAngle);\n"
"    vec3 rotatedTangent = tangent * cosA + bitangent * sinA;\n"
"    vec3 rotatedBitangent = bitangent * cosA - tangent * sinA;\n"
"\n"
"    vec3 rayDirection0 = normalize(centerNormal * 0.60 + rotatedTangent * 0.65 + rotatedBitangent * 0.35);\n"
"    vec3 rayDirection1 = normalize(centerNormal * 0.60 - rotatedTangent * 0.65 - rotatedBitangent * 0.35);\n"
"    vec3 rayDirection2 = normalize(centerNormal * 0.60 - rotatedTangent * 0.65 + rotatedBitangent * 0.35);\n"
"    vec3 rayDirection3 = normalize(centerNormal * 0.60 + rotatedTangent * 0.65 - rotatedBitangent * 0.35);\n"
"    vec3 rayDirection4 = normalize(centerNormal * 0.75 + rotatedTangent * 0.75);\n"
"    vec3 rayDirection5 = normalize(centerNormal * 0.75 - rotatedTangent * 0.75);\n"
"    vec3 rayDirection6 = normalize(centerNormal * 0.75 + rotatedBitangent * 0.75);\n"
"    vec3 rayDirection7 = normalize(centerNormal * 0.75 - rotatedBitangent * 0.75);\n"
"    vec3 rayDirection8 = normalize(centerNormal * 0.65 + rotatedTangent * 0.45 + rotatedBitangent * 0.70);\n"
"    vec3 rayDirection9 = normalize(centerNormal * 0.65 - rotatedTangent * 0.45 - rotatedBitangent * 0.70);\n"
"    vec3 rayDirection10 = normalize(centerNormal * 0.65 - rotatedTangent * 0.45 + rotatedBitangent * 0.70);\n"
"    vec3 rayDirection11 = normalize(centerNormal * 0.65 + rotatedTangent * 0.45 - rotatedBitangent * 0.70);\n"
"\n"
"    vec3 rayOrigin = centerPosition + centerNormal * 0.02;\n"
"\n"
"    vec4 traceResult0 = TraceRadiance(rayOrigin, rayDirection0);\n"
"    vec4 traceResult1 = TraceRadiance(rayOrigin, rayDirection1);\n"
"    vec4 traceResult2 = TraceRadiance(rayOrigin, rayDirection2);\n"
"    vec4 traceResult3 = TraceRadiance(rayOrigin, rayDirection3);\n"
"    vec4 traceResult4 = TraceRadiance(rayOrigin, rayDirection4);\n"
"    vec4 traceResult5 = TraceRadiance(rayOrigin, rayDirection5);\n"
"    vec4 traceResult6 = TraceRadiance(rayOrigin, rayDirection6);\n"
"    vec4 traceResult7 = TraceRadiance(rayOrigin, rayDirection7);\n"
"    vec4 traceResult8 = TraceRadiance(rayOrigin, rayDirection8);\n"
"    vec4 traceResult9 = TraceRadiance(rayOrigin, rayDirection9);\n"
"    vec4 traceResult10 = TraceRadiance(rayOrigin, rayDirection10);\n"
"    vec4 traceResult11 = TraceRadiance(rayOrigin, rayDirection11);\n"
"\n"
"    vec3 gatheredRadiance = vec3(0.0);\n"
"    float validHitCount = 0.0;\n"
"\n"
"    if (traceResult0.a > 0.0) { gatheredRadiance += traceResult0.rgb; validHitCount += 1.0; }\n"
"    if (traceResult1.a > 0.0) { gatheredRadiance += traceResult1.rgb; validHitCount += 1.0; }\n"
"    if (traceResult2.a > 0.0) { gatheredRadiance += traceResult2.rgb; validHitCount += 1.0; }\n"
"    if (traceResult3.a > 0.0) { gatheredRadiance += traceResult3.rgb; validHitCount += 1.0; }\n"
"    if (traceResult4.a > 0.0) { gatheredRadiance += traceResult4.rgb; validHitCount += 1.0; }\n"
"    if (traceResult5.a > 0.0) { gatheredRadiance += traceResult5.rgb; validHitCount += 1.0; }\n"
"    if (traceResult6.a > 0.0) { gatheredRadiance += traceResult6.rgb; validHitCount += 1.0; }\n"
"    if (traceResult7.a > 0.0) { gatheredRadiance += traceResult7.rgb; validHitCount += 1.0; }\n"
"    if (traceResult8.a > 0.0) { gatheredRadiance += traceResult8.rgb; validHitCount += 1.0; }\n"
"    if (traceResult9.a > 0.0) { gatheredRadiance += traceResult9.rgb; validHitCount += 1.0; }\n"
"    if (traceResult10.a > 0.0) { gatheredRadiance += traceResult10.rgb; validHitCount += 1.0; }\n"
"    if (traceResult11.a > 0.0) { gatheredRadiance += traceResult11.rgb; validHitCount += 1.0; }\n"
"\n"
"    if (validHitCount > 0.0)\n"
"    {\n"
"        gatheredRadiance /= validHitCount;\n"
"    }\n"
"\n"
"    vec3 finalColor = gatheredRadiance;\n"
"\n"
"    if (u_gtaoHistoryValid != 0) {\n"
"\n"
"        vec4 previousClip =\n"
"            u_ssgiCurrentViewToPreviousClip *\n"
"            vec4(centerPosition, 1.0);\n"
"\n"
"        bool previousClipValid =\n"
"            previousClip.w > 0.0001;\n"
"\n"
"        vec2 historyUV = vec2(-1.0);\n"
"\n"
"        if (previousClipValid) {\n"
"\n"
"            vec2 previousNDC =\n"
"                previousClip.xy / previousClip.w;\n"
"\n"
"            historyUV =\n"
"                previousNDC * 0.5 + 0.5;\n"
"        }\n"
"\n"
"        bool historyOnScreen =\n"
"            historyUV.x > 0.0 &&\n"
"            historyUV.x < 1.0 &&\n"
"            historyUV.y > 0.0 &&\n"
"            historyUV.y < 1.0;\n"
"\n"
"        if (\n"
"            previousClipValid &&\n"
"            historyOnScreen\n"
"        ) {\n"
"\n"
"            vec4 historySample = texture(\n"
"                u_fragmentMap3,\n"
"                historyUV\n"
"            );\n"
"\n"
"            float historyDepth = texture(\n"
"                u_fragmentMap1,\n"
"                historyUV * u_nonPowerOfTwo.xy\n"
"            ).r;\n"
"\n"
"            bool depthCompatible =\n"
"                abs(historyDepth - centerRawDepth) < 0.001;\n"
"\n"
"            vec3 historyNormal =\n"
"                DecodeGeometricNormal(historyUV);\n"
"\n"
"            bool normalCompatible =\n"
"                dot(\n"
"                    centerNormal,\n"
"                    historyNormal\n"
"                ) > 0.95;\n"
"\n"
"            if (\n"
"                historySample.a > 0.5 &&\n"
"                depthCompatible &&\n"
"                normalCompatible\n"
"            ) {\n"
"\n"
"                finalColor = mix(\n"
"                    gatheredRadiance,\n"
"                    historySample.rgb,\n"
"                    0.0\n"
"                );\n"
"            }\n"
"        }\n"
"    }\n"
"\n"
"    float hitFound =\n"
"        validHitCount > 0.0\n"
"        ? 1.0\n"
"        : 0.0;\n"
"\n"
"    _gl_FragColor = vec4(\n"
"        finalColor,\n"
"        hitFound\n"
"    );\n"
"}\n"
;