GLSL_SHADER const char ES3_SSGI_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform sampler2D u_fragmentMap4;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"\n"
"uniform float u_aoIntensity;\n"
"uniform float u_aoRadius;\n"
"uniform float u_aoThickness;\n"
"uniform float u_aoNormalReject;\n"
"uniform float u_aoSamples;\n"
"uniform int u_gtaoDirections;\n"
"uniform float u_gtaoStrength;\n"
"uniform vec4 u_projectionParams;\n"
"uniform int u_gtaoPass;\n"
"uniform int u_gtaoHistoryValid;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(\n"
"    float depth\n"
")\n"
"{\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"\n"
"    return abs(\n"
"        u_projectionParams.w /\n"
"        (ndcZ + u_projectionParams.z)\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(\n"
"    vec2 uv,\n"
"    float depth\n"
")\n"
"{\n"
"    float viewDepth =\n"
"        ReconstructViewDepth(depth);\n"
"\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"\n"
"    return vec3(\n"
"        ndc.x * viewDepth / u_projectionParams.x,\n"
"        ndc.y * viewDepth / u_projectionParams.y,\n"
"        -viewDepth\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewNormal(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float dC = texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r;\n"
"\n"
"    float dL = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dR = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dD = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float dU = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    vec3 pC = ReconstructViewPosition(uv, dC);\n"
"\n"
"    vec3 pL = ReconstructViewPosition(\n"
"        uv - vec2(texel.x, 0.0),\n"
"        dL\n"
"    );\n"
"\n"
"    vec3 pR = ReconstructViewPosition(\n"
"        uv + vec2(texel.x, 0.0),\n"
"        dR\n"
"    );\n"
"\n"
"    vec3 pD = ReconstructViewPosition(\n"
"        uv - vec2(0.0, texel.y),\n"
"        dD\n"
"    );\n"
"\n"
"    vec3 pU = ReconstructViewPosition(\n"
"        uv + vec2(0.0, texel.y),\n"
"        dU\n"
"    );\n"
"\n"
"    vec3 dx =\n"
"        length(pR - pC) < length(pC - pL)\n"
"        ? pR - pC\n"
"        : pC - pL;\n"
"\n"
"    vec3 dy =\n"
"        length(pU - pC) < length(pC - pD)\n"
"        ? pU - pC\n"
"        : pC - pD;\n"
"\n"
"    vec3 normal = normalize(\n"
"        cross(dx, dy)\n"
"    );\n"
"\n"
"    if (normal.z > 0.0)\n"
"    {\n"
"        normal = -normal;\n"
"    }\n"
"\n"
"    return normal;\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(\n"
"    vec2 uv\n"
")\n"
"{\n"
"    vec4 encodedNormalSample = texture(\n"
"        u_fragmentMap3,\n"
"        uv\n"
"    );\n"
"\n"
"    if (encodedNormalSample.a < 0.5)\n"
"    {\n"
"        return vec3(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0\n"
"        );\n"
"    }\n"
"\n"
"    vec3 normal =\n"
"        encodedNormalSample.xyz * 2.0 - 1.0;\n"
"\n"
"    float normalLengthSquared =\n"
"        dot(normal, normal);\n"
"\n"
"    if (normalLengthSquared < 0.0001)\n"
"    {\n"
"        return vec3(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0\n"
"        );\n"
"    }\n"
"\n"
"    return normal * inversesqrt(\n"
"        normalLengthSquared\n"
"    );\n"
"}\n"
"\n"
"float DebugHorizonSearch(\n"
"    vec2 uv,\n"
"    vec2 dir,\n"
"    vec2 texel,\n"
"    vec3 centerNormal\n"
")\n"
"{\n"
"    float centerRawDepth = texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r;\n"
"\n"
"    vec3 centerPos = ReconstructViewPosition(\n"
"        uv,\n"
"        centerRawDepth\n"
"    );\n"
"\n"
"    float maxHorizon = 0.0;\n"
"\n"
"    for (int i = 1; i <= 8; i++)\n"
"    {\n"
"        float stepRadius =\n"
"            float(i) * 2.0 * u_aoRadius;\n"
"\n"
"        vec2 sampleUV =\n"
"            uv + dir * texel * stepRadius;\n"
"\n"
"        if (sampleUV.x <= 0.0 ||\n"
"            sampleUV.x >= 1.0 ||\n"
"            sampleUV.y <= 0.0 ||\n"
"            sampleUV.y >= 1.0)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float sampleRawDepth = texture(\n"
"            u_fragmentMap1,\n"
"            sampleUV\n"
"        ).r;\n"
"\n"
"        if (sampleRawDepth >= 0.99999)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        vec3 samplePos = ReconstructViewPosition(\n"
"            sampleUV,\n"
"            sampleRawDepth\n"
"        );\n"
"\n"
"        vec3 delta = \n"
"            samplePos - centerPos;\n"
"\n"
"        float viewDistance =\n"
"            length(delta);\n"
"\n"
"        if (viewDistance <= 0.0001)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float depthSeparation = abs(\n"
"            samplePos.z - centerPos.z\n"
"        );\n"
"\n"
"        float thicknessLimit =\n"
"            max(4.0, 32.0 * u_aoThickness);\n"
"\n"
"        float thicknessWeight =\n"
"            1.0 - smoothstep(\n"
"                thicknessLimit * 0.5,\n"
"                thicknessLimit,\n"
"                depthSeparation\n"
"            );\n"
"\n"
"        float rangeLimit =\n"
"            max(16.0, 128.0 * u_aoRadius);\n"
"\n"
"        float distanceWeight =\n"
"            1.0 - smoothstep(\n"
"                rangeLimit * 0.25,\n"
"                rangeLimit,\n"
"                viewDistance\n"
"            );\n"
"\n"
"        vec3 sampleDir =\n"
"            delta / viewDistance;\n"
"\n"
"        float horizonResponse = max(\n"
"            dot(centerNormal, sampleDir),\n"
"            0.0\n"
"        );\n"
"\n"
"        horizonResponse *=\n"
"            thicknessWeight * distanceWeight;\n"
"\n"
"        maxHorizon = max(\n"
"            maxHorizon,\n"
"            horizonResponse\n"
"        );\n"
"    }\n"
"\n"
"    return clamp(\n"
"        maxHorizon,\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructNormal(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"    float dL = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dR = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(texel.x, 0.0)\n"
"    ).r;\n"
"\n"
"    float dD = texture(\n"
"        u_fragmentMap1,\n"
"        uv - vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float dU = texture(\n"
"        u_fragmentMap1,\n"
"        uv + vec2(0.0, texel.y)\n"
"    ).r;\n"
"\n"
"    float normalDepthScale = 450.0;\n"
"\n"
"    vec3 dx = vec3(\n"
"        1.0,\n"
"        0.0,\n"
"        (dR - dL) * normalDepthScale\n"
"    );\n"
"\n"
"    vec3 dy = vec3(\n"
"        0.0,\n"
"        1.0,\n"
"        (dU - dD) * normalDepthScale\n"
"    );\n"
"\n"
"    vec3 n = normalize(\n"
"        cross(dx, dy)\n"
"    );\n"
"\n"
"    return n;\n"
"}\n"
"\n"
"float SampleOcclusion(\n"
"    vec2 uv,\n"
"    vec2 dir,\n"
"    vec2 texel,\n"
"    float radius,\n"
"    float centerDepth,\n"
"    vec3 centerNormal\n"
")\n"
"{\n"
"    vec2 sampleUV =\n"
"        uv + dir * texel * radius;\n"
"\n"
"float sampleDepth = ReconstructViewDepth(\n"
"    texture(\n"
"        u_fragmentMap1,\n"
"        sampleUV\n"
"    ).r\n"
");\n"
"\n"
"    float delta =\n"
"        centerDepth - sampleDepth;\n"
"\n"
"    delta = max(\n"
"        delta - 0.00008,\n"
"        0.0\n"
"    );\n"
"\n"
"    float contactWeight = smoothstep(\n"
"        0.0,\n"
"        0.00035,\n"
"        delta\n"
"    );\n"
"\n"
"    float thicknessWeight =\n"
"        1.0 - smoothstep(\n"
"            0.0008 * u_aoThickness,\n"
"            0.0030 * u_aoThickness,\n"
"            delta\n"
"        );\n"
"\n"
"    vec3 sampleNormal = ReconstructNormal(\n"
"        sampleUV,\n"
"        texel\n"
"    );\n"
"\n"
"    float ndot = clamp(\n"
"        dot(centerNormal, sampleNormal),\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    float normalWeight = mix(\n"
"        u_aoNormalReject,\n"
"        1.0,\n"
"        smoothstep(\n"
"            0.15,\n"
"            0.85,\n"
"            ndot\n"
"        )\n"
"    );\n"
"\n"
"    float radiusWeight =\n"
"        1.0 /\n"
"        (1.0 + radius * 0.1);\n"
"\n"
"    float contribution =\n"
"        delta * delta * 5000.0;\n"
"\n"
"    return\n"
"        contribution *\n"
"        contactWeight *\n"
"        thicknessWeight *\n"
"        normalWeight *\n"
"        radiusWeight;\n"
"}\n"
"\n"
"float ComputeAO(\n"
"    vec2 uv,\n"
"    vec2 texel\n"
")\n"
"{\n"
"float centerDepth =\n"
"ReconstructViewDepth(\n"
"    texture(\n"
"        u_fragmentMap1,\n"
"        uv\n"
"    ).r\n"
");\n"
"\n"
"    vec3 centerNormal = ReconstructNormal(\n"
"        uv,\n"
"        texel\n"
"    );\n"
"\n"
"    vec2 dirs[8];\n"
"\n"
"    dirs[0] = vec2( 1.0,  0.0);\n"
"    dirs[1] = vec2(-1.0,  0.0);\n"
"    dirs[2] = vec2( 0.0,  1.0);\n"
"    dirs[3] = vec2( 0.0, -1.0);\n"
"    dirs[4] = vec2( 0.7071,  0.7071);\n"
"    dirs[5] = vec2(-0.7071,  0.7071);\n"
"    dirs[6] = vec2( 0.7071, -0.7071);\n"
"    dirs[7] = vec2(-0.7071, -0.7071);\n"
"\n"
"    float occlusion = 0.0;\n"
"\n"
"    int directions = clamp(\n"
"        int(u_aoSamples),\n"
"        1,\n"
"        8\n"
"    );\n"
"\n"
"for (int i = 0; i < directions; i++)\n"
"\n"
"    {\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            2.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            4.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            8.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"\n"
"        occlusion += SampleOcclusion(\n"
"            uv,\n"
"            dirs[i],\n"
"            texel,\n"
"            16.0 * u_aoRadius,\n"
"            centerDepth,\n"
"            centerNormal\n"
"        );\n"
"    }\n"
"\n"
"occlusion *= (80.0 * u_aoIntensity);\n"
"\n"
"    float ao = clamp(\n"
"        1.0 - occlusion,\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    ao = smoothstep(\n"
"        0.05,\n"
"        1.0,\n"
"        ao\n"
"    );\n"
"\n"
"    ao = pow(\n"
"        ao,\n"
"        2.0\n"
"    );\n"
"\n"
"    return ao;\n"
"}\n"
"\n"
"float DepthWeight(\n"
"    float centerDepth,\n"
"    float sampleDepth\n"
")\n"
"{\n"
"    float diff = abs(\n"
"        centerDepth - sampleDepth\n"
"    );\n"
"\n"
"    return 1.0 - smoothstep(\n"
"        0.00025,\n"
"        0.0025,\n"
"        diff\n"
"    );\n"
"}\n"
"\n"
"float FilterGTAOVisibility(\n"
"    vec2 historyUV,\n"
"    vec2 texel,\n"
"    vec3 centerNormal\n"
")\n"
"{\n"
"    vec4 centerHistory = texture(\n"
"        u_fragmentMap2,\n"
"        historyUV\n"
"    );\n"
"\n"
"    float centerViewDepth =\n"
"        ReconstructViewDepth(centerHistory.g);\n"
"\n"
"    float visibilitySum =\n"
"        centerHistory.r * 2.0;\n"
"\n"
"    float weightSum = 2.0;\n"
"\n"
"    vec2 offsets[8];\n"
"\n"
"    offsets[0] = vec2(1.0, 0.0);\n"
"    offsets[1] = vec2(-1.0, 0.0);\n"
"    offsets[2] = vec2(0.0, 1.0);\n"
"    offsets[3] = vec2(0.0, -1.0);\n"
"\n"
"    offsets[4] = vec2(1.0, 1.0);\n"
"    offsets[5] = vec2(-1.0, 1.0);\n"
"    offsets[6] = vec2(1.0, -1.0);\n"
"    offsets[7] = vec2(-1.0, -1.0);\n"
"\n"
"    for (int i = 0; i < 8; i++)\n"
"    {\n"
"        vec2 sampleUV =\n"
"            historyUV + offsets[i] * texel;\n"
"\n"
"        vec3 sampleNormal =\n"
"            DecodeGeometricNormal(sampleUV);\n"
"\n"
"        float normalSimilarity = max(\n"
"            dot(centerNormal, sampleNormal),\n"
"            0.0\n"
"        );\n"
"\n"
"        float normalWeight = pow(\n"
"            normalSimilarity,\n"
"            4.0\n"
"        );\n"
"\n"
"        vec4 sampleHistory = texture(\n"
"            u_fragmentMap2,\n"
"            sampleUV\n"
"        );\n"
"\n"
"        float sampleViewDepth =\n"
"            ReconstructViewDepth(sampleHistory.g);\n"
"\n"
"        float depthDifference = abs(\n"
"            centerViewDepth - sampleViewDepth\n"
"        );\n"
"\n"
"        float depthThreshold = max(\n"
"            0.5,\n"
"            centerViewDepth * 0.02\n"
"        );\n"
"\n"
"        float depthWeight =\n"
"            1.0 - smoothstep(\n"
"                depthThreshold * 0.25,\n"
"                depthThreshold,\n"
"                depthDifference\n"
"            );\n"
"\n"
"        float baseWeight =\n"
"            (i < 4)\n"
"            ? 0.75\n"
"            : 0.50;\n"
"\n"
"        float sampleWeight =\n"
"            depthWeight *\n"
"            normalWeight *\n"
"            baseWeight;\n"
"\n"
"        visibilitySum +=\n"
"            sampleHistory.r * sampleWeight;\n"
"\n"
"        weightSum += sampleWeight;\n"
"    }\n"
"\n"
"    return visibilitySum /\n"
"        max(weightSum, 0.0001);\n"
"}\n"
"\n"
"vec4 FilterSSGIRadiance(\n"
"    vec2 radianceUV,\n"
"    vec2 depthUV,\n"
"    vec2 normalUV,\n"
"    vec2 radianceTexel,\n"
"    vec2 depthTexel,\n"
"    float centerRawDepth,\n"
"    vec3 centerNormal\n"
")\n"
"{\n"
"    if (centerRawDepth >= 0.999999)\n"
"    {\n"
"        return vec4(0.0, 0.0, 0.0, 0.0);\n"
"    }\n"
"\n"
"    float centerViewDepth =\n"
"        ReconstructViewDepth(centerRawDepth);\n"
"\n"
"    vec3 radianceSum = vec3(0.0);\n"
"    float weightSum = 0.0;\n"
"\n"
"    vec4 centerSample = texture(\n"
"        u_fragmentMap0,\n"
"        radianceUV\n"
"    );\n"
"\n"
"    if (centerSample.a > 0.5)\n"
"    {\n"
"        radianceSum += centerSample.rgb * 2.0;\n"
"        weightSum += 2.0;\n"
"    }\n"
"\n"
"    vec2 offsets[8];\n"
"\n"
"    offsets[0] = vec2( 1.0,  0.0);\n"
"    offsets[1] = vec2(-1.0,  0.0);\n"
"    offsets[2] = vec2( 0.0,  1.0);\n"
"    offsets[3] = vec2( 0.0, -1.0);\n"
"    offsets[4] = vec2( 1.0,  1.0);\n"
"    offsets[5] = vec2(-1.0,  1.0);\n"
"    offsets[6] = vec2( 1.0, -1.0);\n"
"    offsets[7] = vec2(-1.0, -1.0);\n"
"\n"
"    for (int i = 0; i < 8; ++i)\n"
"    {\n"
"        vec2 offset = offsets[i];\n"
"\n"
"        vec2 sampleRadianceUV = clamp(\n"
"            radianceUV + offset * radianceTexel,\n"
"            vec2(0.0),\n"
"            vec2(1.0)\n"
"        );\n"
"\n"
"        vec4 sampleRadiance = texture(\n"
"            u_fragmentMap0,\n"
"            sampleRadianceUV\n"
"        );\n"
"\n"
"        if (sampleRadiance.a <= 0.5)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        vec2 sampleDepthUV =\n"
"            depthUV + offset * depthTexel;\n"
"\n"
"        float sampleRawDepth = texture(\n"
"            u_fragmentMap1,\n"
"            sampleDepthUV\n"
"        ).r;\n"
"\n"
"        if (sampleRawDepth >= 0.999999)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float sampleViewDepth =\n"
"            ReconstructViewDepth(sampleRawDepth);\n"
"\n"
"        float depthDifference = abs(\n"
"            centerViewDepth - sampleViewDepth\n"
"        );\n"
"\n"
"        float depthThreshold = max(\n"
"            0.05,\n"
"            centerViewDepth * 0.01\n"
"        );\n"
"\n"
"        float depthWeight =\n"
"            1.0 - smoothstep(\n"
"                depthThreshold * 0.25,\n"
"                depthThreshold,\n"
"                depthDifference\n"
"            );\n"
"\n"
"        vec2 sampleNormalUV = clamp(\n"
"            normalUV + offset * radianceTexel,\n"
"            vec2(0.0),\n"
"            vec2(1.0)\n"
"        );\n"
"\n"
"        vec3 sampleNormal =\n"
"            DecodeGeometricNormal(sampleNormalUV);\n"
"\n"
"        float normalSimilarity = max(\n"
"            dot(centerNormal, sampleNormal),\n"
"            0.0\n"
"        );\n"
"\n"
"        float normalWeight = pow(\n"
"            normalSimilarity,\n"
"            2.0\n"
"        );\n"
"\n"
"        float spatialWeight =\n"
"            i < 4\n"
"            ? 1.0\n"
"            : 0.70710678;\n"
"\n"
"        float sampleWeight =\n"
"            depthWeight *\n"
"            normalWeight *\n"
"            spatialWeight;\n"
"\n"
"        radianceSum +=\n"
"            sampleRadiance.rgb * sampleWeight;\n"
"\n"
"        weightSum += sampleWeight;\n"
"    }\n"
"\n"
"    for (int i = 0; i < 8; ++i)\n"
"    {\n"
"        vec2 offset = offsets[i] * 4.0;\n"
"\n"
"        vec2 sampleRadianceUV = clamp(\n"
"            radianceUV + offset * radianceTexel,\n"
"            vec2(0.0),\n"
"            vec2(1.0)\n"
"        );\n"
"\n"
"        vec4 sampleRadiance = texture(\n"
"            u_fragmentMap0,\n"
"            sampleRadianceUV\n"
"        );\n"
"\n"
"        if (sampleRadiance.a <= 0.5)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        vec2 sampleDepthUV =\n"
"            depthUV + offset * depthTexel;\n"
"\n"
"        float sampleRawDepth = texture(\n"
"            u_fragmentMap1,\n"
"            sampleDepthUV\n"
"        ).r;\n"
"\n"
"        if (sampleRawDepth >= 0.999999)\n"
"        {\n"
"            continue;\n"
"        }\n"
"\n"
"        float sampleViewDepth =\n"
"            ReconstructViewDepth(sampleRawDepth);\n"
"\n"
"        float depthDifference = abs(\n"
"            centerViewDepth - sampleViewDepth\n"
"        );\n"
"\n"
"        float depthThreshold = max(\n"
"            0.05,\n"
"            centerViewDepth * 0.01\n"
"        );\n"
"\n"
"        float depthWeight =\n"
"            1.0 - smoothstep(\n"
"                depthThreshold * 0.25,\n"
"                depthThreshold,\n"
"                depthDifference\n"
"            );\n"
"\n"
"        vec2 sampleNormalUV = clamp(\n"
"            normalUV + offset * radianceTexel,\n"
"            vec2(0.0),\n"
"            vec2(1.0)\n"
"        );\n"
"\n"
"        vec3 sampleNormal =\n"
"            DecodeGeometricNormal(sampleNormalUV);\n"
"\n"
"        float normalSimilarity = max(\n"
"            dot(centerNormal, sampleNormal),\n"
"            0.0\n"
"        );\n"
"\n"
"        float normalWeight = pow(\n"
"            normalSimilarity,\n"
"            2.0\n"
"        );\n"
"\n"
"        float spatialWeight =\n"
"            i < 4\n"
"            ? 1.0\n"
"            : 0.70710678;\n"
"\n"
"        float sampleWeight =\n"
"            depthWeight *\n"
"            normalWeight *\n"
"            spatialWeight;\n"
"\n"
"        radianceSum +=\n"
"            sampleRadiance.rgb * sampleWeight;\n"
"\n"
"        weightSum += sampleWeight;\n"
"    }\n"
"\n"
"    if (weightSum <= 0.0001)\n"
"    {\n"
"        return vec4(0.0, 0.0, 0.0, 0.0);\n"
"    }\n"
"\n"
"    vec3 filteredRadiance =\n"
"        radianceSum / weightSum;\n"
"\n"
"    return vec4(\n"
"        filteredRadiance.r,\n"
"        filteredRadiance.g,\n"
"        filteredRadiance.b,\n"
"        1.0\n"
"    );\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    // Normalized full-resolution screen coordinates.\n"
"    vec2 screenUV =\n"
"        gl_FragCoord.xy * u_windowCoords.xy;\n"
"\n"
"    // Full-resolution radiance, normal, and history images.\n"
"    vec2 historyUV = screenUV;\n"
"    vec2 sceneUV = screenUV;\n"
"    vec2 normalUV = screenUV;\n"
"\n"
"    // Preserve the copied scene for pixels that cannot use GTAO/SSGI.\n"
"    vec2 frameUV =\n"
"        screenUV * u_nonPowerOfTwo.xy;\n"
"\n"
"    vec3 sourceSceneColor = texture(\n"
"        u_fragmentMap4,\n"
"        frameUV\n"
"    ).rgb;\n"
"\n"
"    // The preserved depth texture may use an oversized\n"
"    // power-of-two backing allocation.\n"
"    vec2 depthUV =\n"
"        screenUV * u_nonPowerOfTwo.xy;\n"
"\n"
"    vec2 texel = vec2(\n"
"        u_windowCoords.x,\n"
"        u_windowCoords.y\n"
"    );\n"
"\n"
"    // One texel in the oversized preserved-depth texture.\n"
"    vec2 depthTexel =\n"
"        u_windowCoords.xy *\n"
"        u_nonPowerOfTwo.xy;\n"
"\n"
"    vec3 centerGeometricNormal =\n"
"        DecodeGeometricNormal(\n"
"            normalUV\n"
"        );\n"
"\n"
"    if (dot(centerGeometricNormal, centerGeometricNormal) < 0.25)\n"
"    {\n"
"        _gl_FragColor = vec4(\n"
"            sourceSceneColor,\n"
"            1.0\n"
"        );\n"
"\n"
"        return;\n"
"    }\n"
"\n"
"    float centerDepth = texture(\n"
"        u_fragmentMap1,\n"
"        depthUV\n"
"    ).r;\n"
"\n"
"    if (centerDepth >= 0.999999)\n"
"    {\n"
"        _gl_FragColor = vec4(\n"
"            sourceSceneColor,\n"
"            1.0\n"
"        );\n"
"\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 centerPos =\n"
"        ReconstructViewPosition(\n"
"            screenUV,\n"
"            centerDepth\n"
"        );\n"
"\n"
"    if (u_gtaoPass == 2)\n"
"    {\n"
"        vec2 sampleNormalUV = clamp(\n"
"            normalUV + centerGeometricNormal.xy * 0.02,\n"
"            vec2(0.0),\n"
"            vec2(1.0)\n"
"        );\n"
"\n"
"        vec2 sampleSceneUV =\n"
"            sampleNormalUV * u_nonPowerOfTwo.xy;\n"
"\n"
"        vec3 indirectColor = texture(\n"
"            u_fragmentMap0,\n"
"            sampleSceneUV\n"
"        ).rgb;\n"
"\n"
"        _gl_FragColor = vec4(\n"
"            indirectColor,\n"
"            1.0\n"
"        );\n"
"\n"
"        return;\n"
"    }\n"
"    vec2 horizonDirs[16];\n"
"\n"
"horizonDirs[0] = vec2(1.0000, 0.0000);  //   0.0°\n"
"horizonDirs[1] = vec2(0.9239, 0.3827);  //  22.5°\n"
"horizonDirs[2] = vec2(0.7071, 0.7071);  //  45.0°\n"
"horizonDirs[3] = vec2(0.3827, 0.9239);  //  67.5°\n"
"\n"
"horizonDirs[4] = vec2(0.0000, 1.0000);  //  90.0°\n"
"horizonDirs[5] = vec2(-0.3827, 0.9239);  // 112.5°\n"
"horizonDirs[6] = vec2(-0.7071, 0.7071);  // 135.0°\n"
"horizonDirs[7] = vec2(-0.9239, 0.3827);  // 157.5°\n"
"\n"
"horizonDirs[8] = vec2(-1.0000, 0.0000);  // 180.0°\n"
"horizonDirs[9] = vec2(-0.9239, -0.3827);  // 202.5°\n"
"horizonDirs[10] = vec2(-0.7071, -0.7071);  // 225.0°\n"
"horizonDirs[11] = vec2(-0.3827, -0.9239);  // 247.5°\n"
"\n"
"horizonDirs[12] = vec2(0.0000, -1.0000);  // 270.0°\n"
"horizonDirs[13] = vec2(0.3827, -0.9239);  // 292.5°\n"
"horizonDirs[14] = vec2(0.7071, -0.7071);  // 315.0°\n"
"horizonDirs[15] = vec2(0.9239, -0.3827);  // 337.5°\n"
"\n"
"int directions = clamp(\n"
"    u_gtaoDirections,\n"
"    4,\n"
"    16\n"
");\n"
"\n"
"float occlusion = 0.0;\n"
"\n"
"for (int i = 0; i < directions; i++)\n"
"{\n"
"    occlusion += DebugHorizonSearch(\n"
"        depthUV,\n"
"        horizonDirs[i],\n"
"        texel,\n"
"        centerGeometricNormal\n"
"    );\n"
"}\n"
"\n"
"occlusion /= float(directions);\n"
"\n"
"occlusion = clamp(\n"
"    occlusion * u_aoIntensity * 2.0,\n"
"    0.0,\n"
"    1.0\n"
");\n"
"\n"
"float visibility =\n"
"    1.0 - occlusion;\n"
"\n"
"vec4 history = texture(\n"
"    u_fragmentMap2,\n"
"    historyUV\n"
");\n"
"\n"
"float storedVisibility =\n"
"    history.r;\n"
"\n"
"if (u_gtaoPass != 0)\n"
"{\n"
"    storedVisibility = FilterGTAOVisibility(\n"
"        historyUV,\n"
"        texel,\n"
"        centerGeometricNormal\n"
"    );\n"
"}\n"
"\n"
"float storedDepth =\n"
"    history.g;\n"
"\n"
"float historyWeight = 0.8;\n"
"\n"
"float currentViewDepth =\n"
"    ReconstructViewDepth(centerDepth);\n"
"\n"
"float storedViewDepth =\n"
"    ReconstructViewDepth(storedDepth);\n"
"\n"
"float depthDifference = abs(\n"
"    currentViewDepth - storedViewDepth\n"
");\n"
"\n"
"float depthThreshold = max(\n"
"    0.5,\n"
"    currentViewDepth * 0.02\n"
");\n"
"\n"
"if (depthDifference > depthThreshold)\n"
"{\n"
"    historyWeight = 0.0;\n"
"}\n"
"\n"
"if (u_gtaoPass == 0)\n"
"{\n"
"    float temporalVisibility = visibility;\n"
"\n"
"    if (u_gtaoHistoryValid != 0)\n"
"    {\n"
"        temporalVisibility = mix(\n"
"            visibility,\n"
"            storedVisibility,\n"
"            historyWeight\n"
"        );\n"
"    }\n"
"\n"
"_gl_FragColor = vec4(\n"
"    temporalVisibility,\n"
"    centerDepth,\n"
"    0.0,\n"
"    1.0\n"
");\n"
"    return;\n"
"}\n"
"\n"
"// Reconstruct sparse linear SSGI radiance only during\n"
"// the final scene-composite pass.\n"
"vec4 filteredSSGI = FilterSSGIRadiance(\n"
"    sceneUV,\n"
"    depthUV,\n"
"    normalUV,\n"
"    texel,\n"
"    depthTexel,\n"
"    centerDepth,\n"
"    centerGeometricNormal\n"
");\n"
"\n"
"vec3 sceneColor = sourceSceneColor;\n"
"\n"
"// Convert linear SSGI radiance into a bounded contribution.\n"
"vec3 indirectColor = max(\n"
"    filteredSSGI.rgb,\n"
"    vec3(0.0)\n"
");\n"
"\n"
"indirectColor = indirectColor /\n"
"    (indirectColor + vec3(1.0));\n"
"\n"
"float aoFactor = mix(\n"
"    1.0,\n"
"    storedVisibility,\n"
"    u_gtaoStrength\n"
");\n"
"\n"
"vec3 result =\n"
"    sceneColor * aoFactor +\n"
"    indirectColor;\n"
"\n"
"result = clamp(\n"
"    result,\n"
"    vec3(0.0),\n"
"    vec3(1.0)\n"
");\n"
"\n"
"_gl_FragColor = vec4(\n"
"    result,\n"
"    1.0\n"
");\n"
"}\n"
;