GLSL_SHADER const char ES3_SSGI_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform sampler2D u_fragmentMap4;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"\n"
"uniform float u_aoIntensity;\n"
"uniform float u_aoRadius;\n"
"uniform float u_aoThickness;\n"
"uniform float u_aoNormalReject;\n"
"uniform float u_aoSamples;\n"
"uniform int u_gtaoDirections;\n"
"uniform float u_gtaoStrength;\n"
"uniform vec4 u_projectionParams;\n"
"uniform int u_gtaoPass;\n"
"uniform int u_gtaoHistoryValid;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(float depth) {\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"    return abs(u_projectionParams.w / (ndcZ + u_projectionParams.z));\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(vec2 uv, float depth) {\n"
"    float viewDepth = ReconstructViewDepth(depth);\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"    return vec3(ndc.x * viewDepth / u_projectionParams.x, ndc.y * viewDepth / u_projectionParams.y, -viewDepth);\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(vec2 uv) {\n"
"    vec4 encodedNormalSample = texture(u_fragmentMap3, uv);\n"
"    if (encodedNormalSample.a < 0.5) return vec3(0.0, 0.0, 0.0);\n"
"    vec3 normal = encodedNormalSample.xyz * 2.0 - 1.0;\n"
"    float lenSq = dot(normal, normal);\n"
"    return (lenSq < 0.0001) ? vec3(0.0, 0.0, -1.0) : normal * inversesqrt(lenSq);\n"
"}\n"
"\n"
"float SampleOcclusionOptimized(\n"
"    vec2 uv, vec2 dir, vec2 texel, float radius, float centerDepth, vec3 centerNormal\n"
") {\n"
"    vec2 sampleUV = uv + dir * texel * radius;\n"
"    float sampleRawDepth = texture(u_fragmentMap1, sampleUV).r;\n"
"    float sampleViewDepth = ReconstructViewDepth(sampleRawDepth);\n"
"    float delta = max(centerDepth - sampleViewDepth - 0.00008, 0.0);\n"
"    if (delta <= 0.0) return 0.0;\n"
"    float thicknessWeight = 1.0 - smoothstep(0.0008 * u_aoThickness, 0.0030 * u_aoThickness, delta);\n"
"    vec3 sampleNormal = DecodeGeometricNormal(sampleUV);\n"
"    float ndot = clamp(dot(centerNormal, sampleNormal), 0.0, 1.0);\n"
"    float normalWeight = mix(u_aoNormalReject, 1.0, smoothstep(0.15, 0.85, ndot));\n"
"    return (delta * delta * 5000.0) * (1.0 - smoothstep(0.0, 0.00035, delta)) * thicknessWeight * normalWeight * (1.0 / (1.0 + radius * 0.1));\n"
"}\n"
"\n"
"float ComputeAO(vec2 uv, vec2 texel) {\n"
"    float centerDepth = ReconstructViewDepth(texture(u_fragmentMap1, uv).r);\n"
"    vec3 centerNormal = DecodeGeometricNormal(uv);\n"
"    vec2 dirs[8];\n"
"    dirs[0]=vec2(1,0); dirs[1]=vec2(-1,0); dirs[2]=vec2(0,1); dirs[3]=vec2(0,-1);\n"
"    dirs[4]=vec2(0.707,0.707); dirs[5]=vec2(-0.707,0.707); dirs[6]=vec2(0.707,-0.707); dirs[7]=vec2(-0.707,-0.707);\n"
"    float occlusion = 0.0;\n"
"    int directions = clamp(int(u_aoSamples), 1, 8);\n"
"    for (int i = 0; i < directions; i++) {\n"
"        for (int step = 1; step <= 4; step++) {\n"
"            float radiusScale = float(step) * 2.0 * u_aoRadius;\n"
"            occlusion += SampleOcclusionOptimized(uv, dirs[i], texel, radiusScale, centerDepth, centerNormal);\n"
"        }\n"
"    }\n"
"    return pow(smoothstep(0.05, 1.0, clamp(1.0 - (occlusion * u_aoIntensity * 2.0), 0.0, 1.0)), 2.0);\n"
"}\n"
"\n"
"float FilterGTAOVisibility(vec2 historyUV, vec2 texel, vec3 centerNormal) {\n"
"    vec4 centerHistory = texture(u_fragmentMap2, historyUV);\n"
"    float centerViewDepth = ReconstructViewDepth(centerHistory.g);\n"
"    float visibilitySum = centerHistory.r * 2.0;\n"
"    float weightSum = 2.0;\n"
"    vec2 offsets[8];\n"
"    offsets[0]=vec2(1,0); offsets[1]=vec2(-1,0); offsets[2]=vec2(0,1); offsets[3]=vec2(0,-1);\n"
"    offsets[4]=vec2(1,1); offsets[5]=vec2(-1,1); offsets[6]=vec2(1,-1); offsets[7]=vec2(-1,-1);\n"
"    for (int i = 0; i < 8; i++) {\n"
"        vec2 sampleUV = historyUV + offsets[i] * texel;\n"
"        vec4 sampleHistory = texture(u_fragmentMap2, sampleUV);\n"
"        float sampleViewDepth = ReconstructViewDepth(sampleHistory.g);\n"
"        float depthThreshold = max(0.5, centerViewDepth * 0.02);\n"
"        float depthWeight = 1.0 - smoothstep(depthThreshold * 0.25, depthThreshold, abs(centerViewDepth - sampleViewDepth));\n"
"        float normalWeight = pow(max(dot(centerNormal, DecodeGeometricNormal(sampleUV)), 0.0), 4.0);\n"
"        float weight = depthWeight * normalWeight * ((i < 4) ? 0.75 : 0.50);\n"
"        visibilitySum += sampleHistory.r * weight;\n"
"        weightSum += weight;\n"
"    }\n"
"    return visibilitySum / max(weightSum, 0.0001);\n"
"}\n"
"\n"
"vec4 FilterSSGIRadiance(vec2 radianceUV, vec2 depthUV, vec2 normalUV, vec2 radianceTexel, vec2 depthTexel, float centerDepth, vec3 centerNormal) {\n"
"    if (centerDepth >= 0.999999) return vec4(0.0);\n"
"    float centerViewDepth = ReconstructViewDepth(centerDepth);\n"
"    vec3 radianceSum = vec3(0.0); float weightSum = 0.0;\n"
"    vec4 centerSample = texture(u_fragmentMap0, radianceUV);\n"
"    if (centerSample.a > 0.5) { radianceSum += centerSample.rgb * 4.0; weightSum += 4.0; }\n"
"    vec2 offsets[8];\n"
"    offsets[0]=vec2(1,0); offsets[1]=vec2(-1,0); offsets[2]=vec2(0,1); offsets[3]=vec2(0,-1);\n"
"    offsets[4]=vec2(1,1); offsets[5]=vec2(-1,1); offsets[6]=vec2(1,-1); offsets[7]=vec2(-1,-1);\n"
"    for (int i = 0; i < 8; ++i) {\n"
"        for (int scale = 1; scale <= 2; scale++) {\n"
"            vec2 offset = offsets[i] * float(scale);\n"
"            vec2 sRadUV = clamp(radianceUV + offset * radianceTexel, 0.0, 1.0);\n"
"            vec4 sRad = texture(u_fragmentMap0, sRadUV);\n"
"            if (sRad.a <= 0.5) continue;\n"
"            float sDepth = ReconstructViewDepth(texture(u_fragmentMap1, depthUV + offset * depthTexel).r);\n"
"            float dWeight = 1.0 - smoothstep(max(0.05, centerViewDepth * 0.01) * 0.25, max(0.05, centerViewDepth * 0.01), abs(centerViewDepth - sDepth));\n"
"            float nWeight = pow(max(dot(centerNormal, DecodeGeometricNormal(sRadUV)), 0.0), 2.0);\n"
"            float sWeight = dWeight * nWeight * ((i < 4) ? 1.0 : 0.7071);\n"
"            radianceSum += sRad.rgb * sWeight;\n"
"            weightSum += sWeight;\n"
"        }\n"
"    }\n"
"    return (weightSum <= 0.0001) ? vec4(0.0) : vec4(radianceSum / weightSum, 1.0);\n"
"}\n"
"\n"
"void main(void) {\n"
"    vec2 screenUV = gl_FragCoord.xy * u_windowCoords.xy;\n"
"    vec2 frameUV = screenUV * u_nonPowerOfTwo.xy;\n"
"    vec2 depthUV = screenUV * u_nonPowerOfTwo.xy;\n"
"    vec2 texel = u_windowCoords.xy;\n"
"    vec2 depthTexel = u_windowCoords.xy * u_nonPowerOfTwo.xy;\n"
"    vec3 sourceSceneColor = texture(u_fragmentMap4, frameUV).rgb;\n"
"    vec3 centerGeometricNormal = DecodeGeometricNormal(screenUV);\n"
"    if (dot(centerGeometricNormal, centerGeometricNormal) < 0.25) {\n"
"        _gl_FragColor = vec4(sourceSceneColor, 1.0); return;\n"
"    }\n"
"    float centerDepth = texture(u_fragmentMap1, depthUV).r;\n"
"    if (centerDepth >= 0.999999) {\n"
"        _gl_FragColor = vec4(sourceSceneColor, 1.0); return;\n"
"    }\n"
"    if (u_gtaoPass == 2) {\n"
"        vec2 sNormalUV = clamp(screenUV + centerGeometricNormal.xy * 0.02, 0.0, 1.0);\n"
"        _gl_FragColor = vec4(texture(u_fragmentMap0, sNormalUV * u_nonPowerOfTwo.xy).rgb, 1.0);\n"
"        return;\n"
"    }\n"
"    float occlusion = 0.0;\n"
"    if (u_gtaoPass != 0) {\n"
"        int directions = clamp(u_gtaoDirections, 4, 16);\n"
"        vec2 horizonDirs[16];\n"
"        horizonDirs[0]=vec2(1,0); horizonDirs[1]=vec2(0.92,0.38); horizonDirs[2]=vec2(0.7,0.7); horizonDirs[3]=vec2(0.38,0.92);\n"
"        horizonDirs[4]=vec2(0,1); horizonDirs[5]=vec2(-0.38,0.92); horizonDirs[6]=vec2(-0.7,0.7); horizonDirs[7]=vec2(-0.92,0.38);\n"
"        horizonDirs[8]=vec2(-1,0); horizonDirs[9]=vec2(-0.92,-0.38); horizonDirs[10]=vec2(-0.7,-0.7); horizonDirs[11]=vec2(-0.38,-0.92);\n"
"        horizonDirs[12]=vec2(0,-1); horizonDirs[13]=vec2(0.38,-0.92); horizonDirs[14]=vec2(0.7,-0.7); horizonDirs[15]=vec2(0.92,-0.38);\n"
"        for (int i = 0; i < directions; i++) {\n"
"            float maxH = 0.0;\n"
"            for (int j = 1; j <= 8; j++) {\n"
"                float stepR = float(j) * 2.0 * u_aoRadius;\n"
"                vec2 sUV = screenUV + horizonDirs[i] * texel * stepR;\n"
"                if (sUV.x<0.0||sUV.x>1.0||sUV.y<0.0||sUV.y>1.0) continue;\n"
"                float sDepth = texture(u_fragmentMap1, sUV * u_nonPowerOfTwo.xy).r;\n"
"                if (sDepth >= 0.99999) continue;\n"
"                vec3 sPos = ReconstructViewPosition(sUV, sDepth);\n"
"                vec3 cPos = ReconstructViewPosition(screenUV, centerDepth);\n"
"                vec3 delta = sPos - cPos;\n"
"                float vDist = length(delta);\n"
"                if (vDist < 0.0001) continue;\n"
"                float dSep = abs(sPos.z - cPos.z);\n"
"                float tLim = max(4.0, 32.0 * u_aoThickness);\n"
"                float dWeight = 1.0 - smoothstep(tLim*0.5, tLim, dSep);\n"
"                float rLim = max(16.0, 128.0 * u_aoRadius);\n"
"                float distWeight = 1.0 - smoothstep(rLim*0.25, rLim, vDist);\n"
"                maxH = max(maxH, max(dot(centerGeometricNormal, delta/vDist), 0.0) * dWeight * distWeight);\n"
"            }\n"
"            occlusion += maxH;\n"
"        }\n"
"        occlusion = clamp(occlusion/float(directions) * u_aoIntensity * 2.0, 0.0, 1.0);\n"
"    }\n"
"    float visibility = 1.0 - occlusion;\n"
"    if (u_gtaoPass == 0) {\n"
"        if (u_gtaoHistoryValid != 0) {\n"
"            vec4 history = texture(u_fragmentMap2, screenUV);\n"
"            float storedVis = history.r;\n"
"            if (u_gtaoPass != 0) storedVis = FilterGTAOVisibility(screenUV, texel, centerGeometricNormal);\n"
"            float hWeight = 0.6;\n"
"            if (abs(ReconstructViewDepth(centerDepth) - ReconstructViewDepth(history.g)) > max(0.5, ReconstructViewDepth(centerDepth)*0.02)) hWeight = 0.0;\n"
"            visibility = mix(visibility, storedVis, hWeight);\n"
"        }\n"
"        _gl_FragColor = vec4(visibility, centerDepth, 0.0, 1.0); return;\n"
"    }\n"
"    vec4 filteredSSGI = FilterSSGIRadiance(screenUV, depthUV, screenUV, texel, depthTexel, centerDepth, centerGeometricNormal);\n"
"    vec3 sceneColor = texture(u_fragmentMap4, frameUV).rgb;\n"
"    vec3 indirect = clamp(filteredSSGI.rgb / (filteredSSGI.rgb + vec3(1.0)), 0.0, 1.0) * 0.15;\n"
"    float aoFactor = mix(1.0, texture(u_fragmentMap2, screenUV).r, u_gtaoStrength);\n"
"    _gl_FragColor = vec4(clamp(sceneColor * aoFactor + indirect, 0.0, 1.0), 1.0);\n"
"}\n"
;
