GLSL_SHADER const char ES3_SSGI_TRACE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"\n"
"uniform highp vec4 u_projectionParams;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"\n"
"in vec2 var_TexCoord;\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(\n"
"    float depth\n"
")\n"
"{\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"\n"
"    return abs(\n"
"        u_projectionParams.w /\n"
"        (ndcZ + u_projectionParams.z)\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(\n"
"    vec2 uv,\n"
"    float depth\n"
")\n"
"{\n"
"    float viewDepth =\n"
"        ReconstructViewDepth(depth);\n"
"\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"\n"
"    return vec3(\n"
"        ndc.x * viewDepth /\n"
"            u_projectionParams.x,\n"
"\n"
"        ndc.y * viewDepth /\n"
"            u_projectionParams.y,\n"
"\n"
"        -viewDepth\n"
"    );\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(\n"
"    vec2 uv\n"
")\n"
"{\n"
"    vec3 encodedNormal = texture(\n"
"        u_fragmentMap2,\n"
"        uv\n"
"    ).xyz;\n"
"\n"
"    vec3 normal =\n"
"        encodedNormal * 2.0 - 1.0;\n"
"\n"
"    float normalLengthSquared =\n"
"        dot(normal, normal);\n"
"\n"
"    if (normalLengthSquared < 0.0001)\n"
"    {\n"
"        return vec3(\n"
"            0.0,\n"
"            0.0,\n"
"            -1.0\n"
"        );\n"
"    }\n"
"\n"
"    return normal * inversesqrt(\n"
"        normalLengthSquared\n"
"    );\n"
"}\n"
"\n"
"vec2 ProjectViewPosition(\n"
"    vec3 viewPosition\n"
")\n"
"{\n"
"    float safeDepth = max(\n"
"        -viewPosition.z,\n"
"        0.0001\n"
"    );\n"
"\n"
"    vec2 ndc = vec2(\n"
"        viewPosition.x * u_projectionParams.x /\n"
"            safeDepth,\n"
"\n"
"        viewPosition.y * u_projectionParams.y /\n"
"            safeDepth\n"
"    );\n"
"\n"
"    return ndc * 0.5 + 0.5;\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"\n"
"    // ==================================================\n"
"    // 1. SCREEN, DEPTH, AND NORMAL COORDINATES\n"
"    // ==================================================\n"
"    vec2 screenUV =\n"
"        gl_FragCoord.xy * u_windowCoords.xy;\n"
"\n"
"    vec2 depthUV = var_TexCoord;\n"
"    depthUV.y = 0.703125 - depthUV.y;\n"
"\n"
"    float centerRawDepth = texture(\n"
"        u_fragmentMap1,\n"
"        depthUV\n"
"    ).r;\n"
"\n"
"    // ==================================================\n"
"    // 2. CENTER SURFACE RECONSTRUCTION\n"
"    // ==================================================\n"
"    vec3 centerPosition =\n"
"        ReconstructViewPosition(\n"
"            depthUV,\n"
"            centerRawDepth\n"
"        );\n"
"\n"
"    vec3 centerNormal =\n"
"        DecodeGeometricNormal(\n"
"            screenUV\n"
"        );\n"
"\n"
"    // ==================================================\n"
"    // 3. CENTER NORMAL TANGENT BASIS\n"
"    // ==================================================\n"
"\n"
"    vec3 helperAxis =\n"
"        abs(centerNormal.z) < 0.999\n"
"        ? vec3(0.0, 0.0, 1.0)\n"
"        : vec3(0.0, 1.0, 0.0);\n"
"\n"
"    vec3 tangent = normalize(\n"
"        cross(\n"
"            helperAxis,\n"
"            centerNormal\n"
"        )\n"
"    );\n"
"\n"
"    vec3 bitangent = normalize(\n"
"        cross(\n"
"            centerNormal,\n"
"            tangent\n"
"        )\n"
"    );\n"
"\n"
"    // ==================================================\n"
"    // 4. STOCHASTIC RAY ORIENTATION\n"
"    // ==================================================\n"
"    float baseAngle = fract(\n"
"        sin(\n"
"            dot(\n"
"                gl_FragCoord.xy,\n"
"                vec2(12.9898, 78.233)\n"
"            )\n"
"        ) * 43758.5453\n"
"    ) * 6.2831853;\n"
"\n"
"    // ==================================================\n"
"    // 5. TRACE ACCUMULATION\n"
"    // ==================================================\n"
"    float accumulatedDistance = 0.0;\n"
"    float hitCount = 0.0;\n"
"    vec3 accumulatedRadiance = vec3(0.0);\n"
"    float accumulatedWeight = 0.0;\n"
"\n"
"    // ==================================================\n"
"    // 6. RAY GENERATION\n"
"    // ==================================================\n"
"    for (int rayIndex = 0;\n"
"         rayIndex < 4;\n"
"         rayIndex++)\n"
"    {\n"
"        float angle =\n"
"            baseAngle +\n"
"            float(rayIndex) * 1.5707963;\n"
"\n"
"        vec3 localRayDirection = normalize(\n"
"            vec3(\n"
"                cos(angle) * 0.4,\n"
"                sin(angle) * 0.4,\n"
"                0.85\n"
"            )\n"
"        );\n"
"\n"
"        vec3 rayDirection = normalize(\n"
"            tangent * localRayDirection.x +\n"
"            bitangent * localRayDirection.y +\n"
"            centerNormal * localRayDirection.z\n"
"        );\n"
"\n"
"        // Offset the ray origin to reduce self-intersection.\n"
"        // Too small may self-hit; too large may skip nearby geometry.\n"
"        float originBias = 0.05;\n"
"\n"
"        vec3 rayOrigin =\n"
"            centerPosition +\n"
"            centerNormal * originBias;\n"
"\n"
"        float previousDepthDelta = 0.0;\n"
"        bool previousDeltaValid = false;\n"
"\n"
"        // ==============================================\n"
"        // 7. SCREEN-SPACE RAY MARCH\n"
"        // ==============================================\n"
"        for (int stepIndex = 1;\n"
"             stepIndex <= 24;\n"
"             stepIndex++)\n"
"        {\n"
"            float rayDistance =\n"
"                float(stepIndex) * 4.0;\n"
"\n"
"            vec3 rayPosition =\n"
"                rayOrigin +\n"
"                rayDirection * rayDistance;\n"
"\n"
"            if (rayPosition.z >= -0.001)\n"
"            {\n"
"                break;\n"
"            }\n"
"\n"
"            // Project back into the same coordinate space used by\n"
"            // ReconstructViewPosition for depth-buffer access.\n"
"            vec2 sampleDepthUV =\n"
"                ProjectViewPosition(\n"
"                    rayPosition\n"
"                );\n"
"\n"
"            // The valid depth image occupies Y from 0.0 to 0.703125.\n"
"            if (sampleDepthUV.x <= 0.0 ||\n"
"                sampleDepthUV.x >= 1.0 ||\n"
"                sampleDepthUV.y <= 0.0 ||\n"
"                sampleDepthUV.y >= 0.703125)\n"
"            {\n"
"                break;\n"
"            }\n"
"\n"
"            // Convert depth coordinates back into the unflipped\n"
"            // screen coordinate space used by the normal buffer.\n"
"            vec2 sampleScreenUV = vec2(\n"
"                sampleDepthUV.x,\n"
"                0.703125 - sampleDepthUV.y\n"
"            );\n"
"\n"
"            float sampleRawDepth = texture(\n"
"                u_fragmentMap1,\n"
"                sampleDepthUV\n"
"            ).r;\n"
"\n"
"            if (sampleRawDepth >= 0.99999)\n"
"            {\n"
"                previousDeltaValid = false;\n"
"                continue;\n"
"            }\n"
"\n"
"            vec3 scenePosition =\n"
"                ReconstructViewPosition(\n"
"                    sampleDepthUV,\n"
"                    sampleRawDepth\n"
"                );\n"
"\n"
"            float depthDelta =\n"
"                rayPosition.z -\n"
"                scenePosition.z;\n"
"\n"
"            // NOTE: If 'ghost' geometry appears, lower this thickness value.\n"
"            float hitThickness =\n"
"                max(\n"
"                    0.5,\n"
"                    abs(scenePosition.z) * 0.01\n"
"                );\n"
"\n"
"            // ==========================================\n"
"            // 8. SURFACE INTERSECTION TEST\n"
"            // ==========================================\n"
"            bool crossedSurface =\n"
"                previousDeltaValid &&\n"
"                previousDepthDelta > 0.0 &&\n"
"                depthDelta <= 0.0;\n"
"\n"
"            bool insideThickness =\n"
"                depthDelta <= 0.0 &&\n"
"                depthDelta >= -hitThickness;\n"
"\n"
"            bool candidateHit =\n"
"                crossedSurface || insideThickness;\n"
"\n"
"            if (candidateHit)\n"
"            {\n"
"                vec3 hitNormal =\n"
"                    DecodeGeometricNormal(\n"
"                        sampleScreenUV\n"
"                    );\n"
"\n"
"                float hitFacing =\n"
"                    dot(\n"
"                        hitNormal,\n"
"                        -rayDirection\n"
"                    );\n"
"\n"
"                bool frontFacingHit =\n"
"                    hitFacing > 0.10;\n"
"\n"
"                if (frontFacingHit)\n"
"                {\n"
"                    // Convert the accepted screen-space hit into\n"
"                    // the valid region of the scene-color texture.\n"
"                    vec2 hitSceneUV =\n"
"                        sampleScreenUV *\n"
"                        u_nonPowerOfTwo.xy;\n"
"\n"
"                    vec3 hitRadiance = texture(\n"
"                        u_fragmentMap0,\n"
"                        hitSceneUV\n"
"                    ).rgb;\n"
"\n"
"                    // Weight the sample by the outgoing direction\n"
"                    // from the center surface.\n"
"                    float cosineWeight = max(\n"
"                        dot(\n"
"                            centerNormal,\n"
"                            rayDirection\n"
"                        ),\n"
"                        0.0\n"
"                    );\n"
"\n"
"                    // Reduce contributions from distant hits.\n"
"                    float distanceWeight =\n"
"                        1.0 - smoothstep(\n"
"                            8.0,\n"
"                            96.0,\n"
"                            rayDistance\n"
"                        );\n"
"\n"
"                    float hitWeight =\n"
"                        distanceWeight;\n"
"\n"
"                    accumulatedRadiance +=\n"
"                        hitRadiance *\n"
"                        hitWeight;\n"
"\n"
"                    accumulatedWeight +=\n"
"                        hitWeight;\n"
"\n"
"                    accumulatedDistance +=\n"
"                        rayDistance;\n"
"\n"
"                    hitCount += 1.0;\n"
"                    break;\n"
"                }\n"
"\n"
"			 previousDeltaValid = false;\n"
"                continue;\n"
"            }\n"
"\n"
"            previousDepthDelta = depthDelta;\n"
"            previousDeltaValid = true;\n"
"        }\n"
"    }\n"
"\n"
"    // ==================================================\n"
"    // 9. FINAL INDIRECT RADIANCE RESULT\n"
"    // ==================================================\n"
"    if (hitCount <= 0.0 ||\n"
"        accumulatedWeight <= 0.0001)\n"
"    {\n"
"        _gl_FragColor = vec4(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0,\n"
"            1.0\n"
"        );\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 indirectRadiance =\n"
"        accumulatedRadiance /\n"
"        max(accumulatedWeight, 0.0001);\n"
"\n"
"    // Debug exposure only. This does not change tracing.\n"
"    vec3 debugRadiance =\n"
"        sqrt(\n"
"            max(\n"
"                indirectRadiance,\n"
"                vec3(0.0)\n"
"            )\n"
"        );\n"
"\n"
"    _gl_FragColor = vec4(\n"
"        debugRadiance,\n"
"        1.0\n"
"    );\n"
"}\n"
;
