GLSL_SHADER const char ES3_SSGI_TRACE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0; // Radiance\n"
"uniform sampler2D u_fragmentMap1; // Depth\n"
"uniform sampler2D u_fragmentMap2; // Normals\n"
"uniform sampler2D u_fragmentMap3; // History\n"
"\n"
"uniform highp vec4 u_projectionParams;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform int u_gtaoHistoryValid;\n"
"uniform highp mat4 u_ssgiCurrentViewToPreviousClip;\n"
"uniform highp vec4 u_uniformParm0;\n"
"\n"
"in vec2 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(float depth) {\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"    return abs(u_projectionParams.w / (ndcZ + u_projectionParams.z));\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(vec2 uv, float depth) {\n"
"    float viewDepth = ReconstructViewDepth(depth);\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"    return vec3(ndc.x * viewDepth / u_projectionParams.x, ndc.y * viewDepth / u_projectionParams.y, -viewDepth);\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(vec2 uv) {\n"
"    vec4 encodedNormalSample = texture(u_fragmentMap2, uv);\n"
"    if (encodedNormalSample.a < 0.5) return vec3(0.0, 0.0, 0.0);\n"
"    vec3 normal = encodedNormalSample.xyz * 2.0 - 1.0;\n"
"    float lenSq = dot(normal, normal);\n"
"    if (lenSq < 0.0001) return vec3(0.0, 0.0, -1.0);\n"
"    return normal * inversesqrt(lenSq);\n"
"}\n"
"\n"
"vec2 ProjectViewPosition(vec3 viewPosition) {\n"
"    float safeDepth = max(-viewPosition.z, 0.0001);\n"
"    vec2 ndc = vec2(viewPosition.x * u_projectionParams.x / safeDepth, viewPosition.y * u_projectionParams.y / safeDepth);\n"
"    return ndc * 0.5 + 0.5;\n"
"}\n"
"\n"
"float InterleavedGradientNoise(vec2 pixelPosition) {\n"
"    return fract(52.9829189 * fract(dot(pixelPosition, vec2(0.06711056, 0.00583715))));\n"
"}\n"
"\n"
"vec4 TraceRadiance(vec3 rayOrigin, vec3 rayDirection) {\n"
"    const int TRACE_STEP_COUNT = 24;\n"
"    const float TRACE_STEP_LENGTH = 0.0416667;\n"
"    float previousDepthDifference = -1.0;\n"
"    bool previousDepthValid = false;\n"
"    for (int stepIndex = 1; stepIndex <= TRACE_STEP_COUNT; ++stepIndex) {\n"
"        float rayDistance = float(stepIndex) * TRACE_STEP_LENGTH;\n"
"        vec3 testPosition = rayOrigin + rayDirection * rayDistance;\n"
"        vec2 testScreenUV = ProjectViewPosition(testPosition);\n"
"        if (testScreenUV.x <= 0.0 || testScreenUV.x >= 1.0 || testScreenUV.y <= 0.0 || testScreenUV.y >= 1.0) break;\n"
"        vec2 testDepthUV = testScreenUV * u_nonPowerOfTwo.xy;\n"
"        float sampledRawDepth = texture(u_fragmentMap1, testDepthUV).r;\n"
"        if (sampledRawDepth >= 0.999999) { previousDepthValid = false; continue; }\n"
"        vec3 sampledScenePosition = ReconstructViewPosition(testScreenUV, sampledRawDepth);\n"
"        float signedDepthDifference = sampledScenePosition.z - testPosition.z;\n"
"        float hitThickness = max(TRACE_STEP_LENGTH * 1.0, abs(sampledScenePosition.z) * 0.002);\n"
"        bool crossedSurface = previousDepthValid && previousDepthDifference <= 0.0 && signedDepthDifference > 0.0;\n"
"        bool thinSurfaceHit = signedDepthDifference > 0.0 && signedDepthDifference < hitThickness;\n"
"        if (crossedSurface || thinSurfaceHit) {\n"
"            vec3 hitNormal = DecodeGeometricNormal(testScreenUV);\n"
"            float hitFacing = max(dot(hitNormal, -rayDirection), 0.0);\n"
"            if (hitFacing > 0.25) {\n"
"                vec3 hitRadiance = texture(u_fragmentMap0, testScreenUV).rgb;\n"
"                float hitLuminance = dot(hitRadiance, vec3(0.2126, 0.7152, 0.0722));\n"
"                const float radianceLimit = 2.0;\n"
"                if (hitLuminance > radianceLimit) {\n"
"                    hitRadiance *= (radianceLimit / max(hitLuminance, 0.0001));\n"
"                }\n"
"                return vec4(hitRadiance * hitFacing, hitFacing);\n"
"            }\n"
"        }\n"
"        previousDepthDifference = signedDepthDifference;\n"
"        previousDepthValid = true;\n"
"    }\n"
"    return vec4(0.0);\n"
"}\n"
"\n"
"void main(void) {\n"
"    vec2 depthUV = vec2(var_TexCoord.x * u_nonPowerOfTwo.x, (1.0 - var_TexCoord.y) * u_nonPowerOfTwo.y);\n"
"    vec2 screenUV = vec2(var_TexCoord.x, 1.0 - var_TexCoord.y);\n"
"    float centerRawDepth = texture(u_fragmentMap1, depthUV).r;\n"
"\n"
"    if (centerRawDepth >= 0.999999) {\n"
"        _gl_FragColor = vec4(0.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 centerPosition = ReconstructViewPosition(screenUV, centerRawDepth);\n"
"    vec3 centerNormal = DecodeGeometricNormal(screenUV);\n"
"    if (dot(centerNormal, centerNormal) < 0.25) {\n"
"        _gl_FragColor = vec4(0.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 helperAxis = abs(centerNormal.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(0.0, 1.0, 0.0);\n"
"    vec3 tangent = normalize(cross(helperAxis, centerNormal));\n"
"    vec3 bitangent = normalize(cross(centerNormal, tangent));\n"
"    float noise = InterleavedGradientNoise(gl_FragCoord.xy);\n"
"    float rotAngle = noise * 6.2831853;\n"
"    float sinA = sin(rotAngle), cosA = cos(rotAngle);\n"
"    vec3 rotatedTangent = tangent * cosA + bitangent * sinA;\n"
"    vec3 rotatedBitangent = bitangent * cosA - tangent * sinA;\n"
"    vec3 rayDirection = normalize(centerNormal * 0.6 + rotatedTangent * 0.4);\n"
"    vec3 rayOrigin = centerPosition + centerNormal * 0.02;\n"
"    vec4 traceResult = TraceRadiance(rayOrigin, rayDirection);\n"
"    vec3 gatheredRadiance = traceResult.rgb;\n"
"    float hitFound = traceResult.a > 0.0 ? 1.0 : 0.0;\n"
"\n"
"    if (u_gtaoHistoryValid != 0) {\n"
"        vec4 previousClip = u_ssgiCurrentViewToPreviousClip * vec4(centerPosition, 1.0);\n"
"        if (previousClip.w > 0.0001) {\n"
"            vec2 historyUV = (previousClip.xy / previousClip.w) * 0.5 + 0.5;\n"
"            if (historyUV.x > 0.0 && historyUV.x < 1.0 && historyUV.y > 0.0 && historyUV.y < 1.0) {\n"
"                vec4 historySample = texture(u_fragmentMap3, historyUV);\n"
"                float historyDepth = texture(u_fragmentMap1, historyUV * u_nonPowerOfTwo.xy).r;\n"
"                bool depthCompatible = abs(historyDepth - centerRawDepth) < 0.001;\n"
"                vec3 historyNormal = DecodeGeometricNormal(historyUV);\n"
"                bool normalCompatible = dot(centerNormal, historyNormal) > 0.95;\n"
"                if (historySample.a > 0.5 && depthCompatible && normalCompatible) {\n"
"                    gatheredRadiance = mix(gatheredRadiance, historySample.rgb, 0.95);\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    _gl_FragColor = vec4(gatheredRadiance, hitFound);\n"
"}\n";
