GLSL_SHADER const char ES3_SSGI_TRACE_FRAG[] =
"#version 300 es\n"
"\n"
"precision highp float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"\n"
"uniform highp vec4 u_projectionParams;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform int u_gtaoHistoryValid;\n"
"uniform highp vec4 u_uniformParm0;\n"
"\n"
"in vec2 var_TexCoord;\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"float ReconstructViewDepth(\n"
"    float depth\n"
")\n"
"{\n"
"    float ndcZ = depth * 2.0 - 1.0;\n"
"\n"
"    return abs(\n"
"        u_projectionParams.w /\n"
"        (ndcZ + u_projectionParams.z)\n"
"    );\n"
"}\n"
"\n"
"vec3 ReconstructViewPosition(\n"
"    vec2 uv,\n"
"    float depth\n"
")\n"
"{\n"
"    float viewDepth =\n"
"        ReconstructViewDepth(depth);\n"
"\n"
"    vec2 ndc = uv * 2.0 - 1.0;\n"
"\n"
"    return vec3(\n"
"        ndc.x * viewDepth /\n"
"            u_projectionParams.x,\n"
"\n"
"        ndc.y * viewDepth /\n"
"            u_projectionParams.y,\n"
"\n"
"        -viewDepth\n"
"    );\n"
"}\n"
"\n"
"vec3 DecodeGeometricNormal(\n"
"    vec2 uv\n"
")\n"
"{\n"
"    vec4 encodedNormalSample = texture(\n"
"        u_fragmentMap2,\n"
"        uv\n"
"    );\n"
"\n"
"    if (encodedNormalSample.a < 0.5)\n"
"    {\n"
"        return vec3(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0\n"
"        );\n"
"    }\n"
"\n"
"    vec3 normal =\n"
"        encodedNormalSample.xyz * 2.0 - 1.0;\n"
"\n"
"    float normalLengthSquared =\n"
"        dot(normal, normal);\n"
"\n"
"    if (normalLengthSquared < 0.0001)\n"
"    {\n"
"        return vec3(\n"
"            0.0,\n"
"            0.0,\n"
"            -1.0\n"
"        );\n"
"    }\n"
"\n"
"    return normal * inversesqrt(\n"
"        normalLengthSquared\n"
"    );\n"
"}\n"
"\n"
"vec2 ProjectViewPosition(\n"
"    vec3 viewPosition\n"
")\n"
"{\n"
"    float safeDepth = max(\n"
"        -viewPosition.z,\n"
"        0.0001\n"
"    );\n"
"\n"
"    vec2 ndc = vec2(\n"
"        viewPosition.x * u_projectionParams.x /\n"
"            safeDepth,\n"
"\n"
"        viewPosition.y * u_projectionParams.y /\n"
"            safeDepth\n"
"    );\n"
"\n"
"    return ndc * 0.5 + 0.5;\n"
"}\n"
"\n"
"vec4 TraceRadiance(\n"
"    vec3 rayOrigin,\n"
"    vec3 rayDirection\n"
")\n"
"{\n"
"    const int TRACE_STEP_COUNT = 24;\n"
"    const float TRACE_STEP_LENGTH = 0.0416667;\n"
"\n"
"    float previousDepthDifference = -1.0;\n"
"    bool previousDepthValid = false;\n"
"\n"
"    for (int stepIndex = 1;\n"
"         stepIndex <= TRACE_STEP_COUNT;\n"
"         ++stepIndex)\n"
"    {\n"
"        float rayDistance =\n"
"            float(stepIndex) * TRACE_STEP_LENGTH;\n"
"\n"
"        vec3 testPosition =\n"
"            rayOrigin +\n"
"            rayDirection * rayDistance;\n"
"\n"
"        vec2 testScreenUV =\n"
"            ProjectViewPosition(testPosition);\n"
"\n"
"        bool projectedOnScreen =\n"
"            testScreenUV.x > 0.0 &&\n"
"            testScreenUV.x < 1.0 &&\n"
"            testScreenUV.y > 0.0 &&\n"
"            testScreenUV.y < 1.0;\n"
"\n"
"        if (!projectedOnScreen)\n"
"        {\n"
"            break;\n"
"        }\n"
"\n"
"        vec2 testDepthUV = vec2(\n"
"            testScreenUV.x * u_nonPowerOfTwo.x,\n"
"            testScreenUV.y * u_nonPowerOfTwo.y\n"
"        );\n"
"\n"
"        float sampledRawDepth = texture(\n"
"            u_fragmentMap1,\n"
"            testDepthUV\n"
"        ).r;\n"
"\n"
"        if (sampledRawDepth >= 0.999999)\n"
"        {\n"
"            previousDepthValid = false;\n"
"            continue;\n"
"        }\n"
"\n"
"        vec3 sampledScenePosition =\n"
"            ReconstructViewPosition(\n"
"                testScreenUV,\n"
"                sampledRawDepth\n"
"            );\n"
"\n"
"        float signedDepthDifference =\n"
"            sampledScenePosition.z -\n"
"            testPosition.z;\n"
"\n"
"        float hitThickness = max(\n"
"            TRACE_STEP_LENGTH * 1.0,\n"
"            abs(sampledScenePosition.z) * 0.002\n"
"        );\n"
"\n"
"        bool crossedSurface =\n"
"            previousDepthValid &&\n"
"            previousDepthDifference <= 0.0 &&\n"
"            signedDepthDifference > 0.0;\n"
"\n"
"        bool thinSurfaceHit =\n"
"            signedDepthDifference > 0.0 &&\n"
"            signedDepthDifference < hitThickness;\n"
"\n"
"        vec3 hitNormal =\n"
"            DecodeGeometricNormal(testScreenUV);\n"
"\n"
"        if (dot(hitNormal, hitNormal) < 0.25)\n"
"        {\n"
"            previousDepthDifference =\n"
"                signedDepthDifference;\n"
"\n"
"            previousDepthValid = true;\n"
"            continue;\n"
"        }\n"
"\n"
"        float hitFacing = max(\n"
"            dot(\n"
"                hitNormal,\n"
"                -rayDirection\n"
"            ),\n"
"            0.0\n"
"        );\n"
"\n"
"        bool geometricHit =\n"
"            crossedSurface ||\n"
"            thinSurfaceHit;\n"
"\n"
"        // Do not terminate the ray at a back-facing candidate.\n"
"        // Continue marching until a useful receiving surface is found.\n"
"        bool acceptedHit =\n"
"            geometricHit &&\n"
"            hitFacing > 0.10;\n"
"\n"
"        if (acceptedHit)\n"
"        {\n"
"            vec3 hitRadiance = texture(\n"
"                u_fragmentMap0,\n"
"                testScreenUV\n"
"            ).rgb;\n"
"\n"
"            hitRadiance *= hitFacing;\n"
"\n"
"            return vec4(\n"
"                hitRadiance.r,\n"
"                hitRadiance.g,\n"
"                hitRadiance.b,\n"
"                hitFacing\n"
"            );\n"
"        }\n"
"\n"
"        previousDepthDifference =\n"
"            signedDepthDifference;\n"
"\n"
"        previousDepthValid = true;\n"
"    }\n"
"\n"
"    return vec4(\n"
"        0.0,\n"
"        0.0,\n"
"        0.0,\n"
"        0.0\n"
"    );\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    // 1. COORDINATE SETUP\n"
"    vec2 depthUV = vec2(\n"
"        var_TexCoord.x * u_nonPowerOfTwo.x,\n"
"        (1.0 - var_TexCoord.y) * u_nonPowerOfTwo.y\n"
"    );\n"
"\n"
"    vec2 screenUV = vec2(\n"
"        var_TexCoord.x,\n"
"        1.0 - var_TexCoord.y\n"
"    );\n"
"\n"
"    // 2. RECONSTRUCTION\n"
"    float centerRawDepth = texture(u_fragmentMap1, depthUV).r;\n"
"\n"
"    if (centerRawDepth >= 0.999999)\n"
"    {\n"
"        _gl_FragColor = vec4(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0,\n"
"            0.0\n"
"        );\n"
"\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 centerPosition = ReconstructViewPosition(\n"
"        screenUV,\n"
"        centerRawDepth\n"
"    );\n"
"\n"
"    vec3 centerNormal = DecodeGeometricNormal(screenUV);\n"
"\n"
"    if (dot(centerNormal, centerNormal) < 0.25)\n"
"    {\n"
"        _gl_FragColor = vec4(\n"
"            0.0,\n"
"            0.0,\n"
"            0.0,\n"
"            0.0\n"
"        );\n"
"\n"
"        return;\n"
"    }\n"
"\n"
"    // 3. EIGHT-RAY HEMISPHERE TRACE\n"
"    vec3 helperAxis =\n"
"        abs(centerNormal.z) < 0.999\n"
"        ? vec3(0.0, 0.0, 1.0)\n"
"        : vec3(0.0, 1.0, 0.0);\n"
"\n"
"    vec3 tangent = normalize(\n"
"        cross(helperAxis, centerNormal)\n"
"    );\n"
"\n"
"    vec3 bitangent = normalize(\n"
"        cross(centerNormal, tangent)\n"
"    );\n"
"\n"
"    // Rotate the hemisphere pattern by 22.5 degrees per phase.\n"
"    float rotationAngle = 0.0;\n"
"\n"
"    float rotationSine =\n"
"        sin(rotationAngle);\n"
"\n"
"    float rotationCosine =\n"
"        cos(rotationAngle);\n"
"\n"
"    vec3 rotatedTangent =\n"
"        tangent * rotationCosine +\n"
"        bitangent * rotationSine;\n"
"\n"
"    vec3 rotatedBitangent =\n"
"        bitangent * rotationCosine -\n"
"        tangent * rotationSine;\n"
"\n"
"    vec3 rayDirection0 = normalize(\n"
"        centerNormal * 0.60 +\n"
"        rotatedTangent * 0.65 +\n"
"        rotatedBitangent * 0.35\n"
"    );\n"
"\n"
"    vec3 rayDirection1 = normalize(\n"
"        centerNormal * 0.60 -\n"
"        rotatedTangent * 0.65 -\n"
"        rotatedBitangent * 0.35\n"
"    );\n"
"\n"
"    vec3 rayDirection2 = normalize(\n"
"        centerNormal * 0.60 -\n"
"        rotatedTangent * 0.65 +\n"
"        rotatedBitangent * 0.35\n"
"    );\n"
"\n"
"    vec3 rayDirection3 = normalize(\n"
"        centerNormal * 0.60 +\n"
"        rotatedTangent * 0.65 -\n"
"        rotatedBitangent * 0.35\n"
"    );\n"
"\n"
"    vec3 rayDirection4 = normalize(\n"
"        centerNormal * 0.75 +\n"
"        rotatedTangent * 0.75\n"
"    );\n"
"\n"
"    vec3 rayDirection5 = normalize(\n"
"        centerNormal * 0.75 -\n"
"        rotatedTangent * 0.75\n"
"    );\n"
"\n"
"    vec3 rayDirection6 = normalize(\n"
"        centerNormal * 0.75 +\n"
"        rotatedBitangent * 0.75\n"
"    );\n"
"\n"
"    vec3 rayDirection7 = normalize(\n"
"        centerNormal * 0.75 -\n"
"        rotatedBitangent * 0.75\n"
"    );\n"
"\n"
"    vec3 rayDirection8 = normalize(\n"
"        centerNormal * 0.65 +\n"
"        rotatedTangent * 0.45 +\n"
"        rotatedBitangent * 0.70\n"
"    );\n"
"\n"
"    vec3 rayDirection9 = normalize(\n"
"        centerNormal * 0.65 -\n"
"        rotatedTangent * 0.45 -\n"
"        rotatedBitangent * 0.70\n"
"    );\n"
"\n"
"    vec3 rayDirection10 = normalize(\n"
"        centerNormal * 0.65 -\n"
"        rotatedTangent * 0.45 +\n"
"        rotatedBitangent * 0.70\n"
"    );\n"
"\n"
"    vec3 rayDirection11 = normalize(\n"
"        centerNormal * 0.65 +\n"
"        rotatedTangent * 0.45 -\n"
"        rotatedBitangent * 0.70\n"
"    );\n"
"\n"
"    vec3 rayOrigin =\n"
"        centerPosition +\n"
"        centerNormal * 0.02;\n"
"\n"
"    vec4 traceResult0 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection0\n"
"    );\n"
"\n"
"    vec4 traceResult1 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection1\n"
"    );\n"
"\n"
"    vec4 traceResult2 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection2\n"
"    );\n"
"\n"
"    vec4 traceResult3 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection3\n"
"    );\n"
"    vec4 traceResult4 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection4\n"
"    );\n"
"\n"
"    vec4 traceResult5 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection5\n"
"    );\n"
"\n"
"    vec4 traceResult6 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection6\n"
"    );\n"
"\n"
"    vec4 traceResult7 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection7\n"
"    );\n"
"\n"
"    vec4 traceResult8 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection8\n"
"    );\n"
"\n"
"    vec4 traceResult9 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection9\n"
"    );\n"
"\n"
"    vec4 traceResult10 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection10\n"
"    );\n"
"\n"
"    vec4 traceResult11 = TraceRadiance(\n"
"        rayOrigin,\n"
"        rayDirection11\n"
"    );\n"
"\n"
"    float validHitCount =\n"
"        traceResult0.a +\n"
"        traceResult1.a +\n"
"        traceResult2.a +\n"
"        traceResult3.a +\n"
"        traceResult4.a +\n"
"        traceResult5.a +\n"
"        traceResult6.a +\n"
"        traceResult7.a +\n"
"        traceResult8.a +\n"
"        traceResult9.a +\n"
"        traceResult10.a +\n"
"        traceResult11.a;\n"
"\n"
"    vec3 gatheredRadiance =\n"
"        traceResult0.rgb +\n"
"        traceResult1.rgb +\n"
"        traceResult2.rgb +\n"
"        traceResult3.rgb +\n"
"        traceResult4.rgb +\n"
"        traceResult5.rgb +\n"
"        traceResult6.rgb +\n"
"        traceResult7.rgb +\n"
"        traceResult8.rgb +\n"
"        traceResult9.rgb +\n"
"        traceResult10.rgb +\n"
"        traceResult11.rgb;\n"
"\n"
"    if (validHitCount > 0.0)\n"
"    {\n"
"        gatheredRadiance /= validHitCount;\n"
"    }\n"
"\n"
"    bool currentValid =\n"
"        validHitCount > 0.0;\n"
"\n"
"    vec4 historySample = texture(\n"
"        u_fragmentMap3,\n"
"        screenUV\n"
"    );\n"
"\n"
"    bool historyValid =\n"
"        u_gtaoHistoryValid != 0 &&\n"
"        historySample.a > 0.5;\n"
"\n"
"    if (\n"
"        currentValid &&\n"
"        historyValid\n"
"    )\n"
"    {\n"
"        gatheredRadiance = mix(\n"
"            gatheredRadiance,\n"
"            historySample.rgb,\n"
"            0.80\n"
"        );\n"
"    }\n"
"\n"
"    float hitFound =\n"
"        currentValid\n"
"        ? 1.0\n"
"        : 0.0;\n"
"\n"
"    // Store linear HDR radiance for reconstruction and compositing.\n"
"    _gl_FragColor = vec4(\n"
"        gatheredRadiance.r,\n"
"        gatheredRadiance.g,\n"
"        gatheredRadiance.b,\n"
"        hitFound\n"
"    );\n"
"\n"
"    // MODE 4: Normal Visualization\n"
"    /*\n"
"    _gl_FragColor = vec4(centerNormal * 0.5 + 0.5, 1.0);\n"
"    */\n"
"}\n"
;